import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// 支持的语言类型
export type Language = 'en' | 'ja' | 'zh' | 'ko' | 'fr' | 'pt' | 'es' | 'de';

// 语言配置
export const LANGUAGES: { id: Language; name: string; nativeName: string; flag: string }[] = [
  { id: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { id: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { id: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { id: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { id: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { id: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { id: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { id: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
];

// 翻译字典
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.community': 'Community',
    'nav.inspire': 'Inspire',
    'nav.blog': 'Blog',
    'nav.artists': 'Artists',
    'nav.upgrade': 'Upgrade',
    'nav.apply_artist': 'Apply Artist',
    'nav.sign_in': 'Sign In',
    'nav.profile': 'Profile',
    'nav.notifications': 'Notifications',
    'nav.post': 'Post',
    'nav.alerts': 'Alerts',
    'nav.me': 'Me',
    
    // Home Page - Popular Styles
    'home.popular_styles': 'Popular Tattoo Styles',
    'home.explore_all': 'Explore All',
    'home.trending': 'Trending',

    // AI Generator
    'ai.title': 'AI Tattoo Generator',
    'ai.subtitle': 'Create stunning Chinese traditional tattoo designs with AI',
    'ai.style': 'Style',
    'ai.body_part': 'Body Part',
    'ai.prompt_placeholder': 'Describe your tattoo idea...',
    'ai.generate': 'Generate Tattoo',
    'ai.generating': 'Generating...',
    'ai.sign_in_to_generate': 'Sign In to Generate',
    'ai.preview': 'Preview',
    'ai.download': 'Download HD',
    'ai.share': 'Share',
    'ai.your_design': 'Your tattoo design will appear here',
    'ai.upload_image': 'Upload reference image',
    'ai.analyzing': 'Analyzing cultural meaning...',

    // Pricing (basic)
    'pricing.free': 'Free',
    'pricing.monthly': 'Monthly',
    'pricing.yearly': 'Yearly',
    'pricing.lifetime': 'Lifetime',
    'pricing.per_day': '/day',
    'pricing.per_month': '/month',
    'pricing.per_year': '/year',
    'pricing.generations': 'generations',
    'pricing.watermark': 'Watermark',
    'pricing.no_watermark': 'No Watermark',
    'pricing.upgrade': 'Upgrade Now',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',

    // Body Parts
    'body.arm': 'Arm',
    'body.back': 'Back',
    'body.chest': 'Chest',
    'body.wrist': 'Wrist',
    'body.collarbone': 'Collarbone',
    'body.thigh': 'Thigh',
    'body.calf': 'Calf',

    // Auth - Login
    'auth.welcome_back': 'Welcome Back',
    'auth.sign_in_to_continue': 'Sign in to continue your journey',
    'auth.sign_in': 'Sign In',
    'auth.signing_in': 'Signing in...',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.enter_email': 'Enter your email',
    'auth.enter_password': 'Enter your password',
    'auth.no_account': "Don't have an account?",
    'auth.sign_up_link': 'Sign up',
    'auth.forgot_password': 'Forgot password?',

    // Auth - Register
    'auth.create_account': 'Create Account',
    'auth.join_community': 'Join InkAI.life community',
    'auth.username': 'Username',
    'auth.choose_username': 'Choose a username',
    'auth.create_password': 'Create a password',
    'auth.creating': 'Creating...',
    'auth.has_account': 'Already have an account?',
    'auth.sign_in_link': 'Sign in',
    'auth.agree_terms': 'I agree to the',
    'auth.terms_of_service': 'Terms of Service',
    'auth.sign_up': 'Sign Up',
    'auth.sign_in_required': 'Sign in required',
    'auth.sign_in_desc': 'Please sign in to continue',
    'auth.login_to_post': 'Sign in to share your work',
    'auth.login_to_post_desc': 'Join our community of tattoo enthusiasts',
    'auth.login_to_like': 'Sign in to like',
    'auth.login_to_like_desc': 'Show your appreciation for amazing artwork',
    'auth.login_to_comment': 'Sign in to comment',
    'auth.login_to_comment_desc': 'Share your thoughts with the community',
    'auth.login_to_generate': 'Sign in to create',
    'auth.login_to_generate_desc': 'Access AI-powered tattoo design tools',
    'auth.login_to_save': 'Sign in to save',
    'auth.login_to_save_desc': 'Bookmark your favorite tattoo designs',
    'auth.login_to_follow': 'Sign in to follow',
    'auth.login_to_follow_desc': 'Connect with your favorite artists',
    'auth.confirm_email': 'Check your email',
    'auth.go_to_signin': 'Go to Sign In',
    
    // Profile
    'profile.settings': 'Settings',
    'profile.display_name': 'Display Name',

    // Styles
    'style.oriental': 'Oriental',
    'style.japanese': 'Japanese',
    'style.american_traditional': 'American Traditional',
    'style.neo_traditional': 'Neo-Traditional',
    'style.blackwork': 'Dark & Blackwork',
    'style.watercolor': 'Watercolor',
    'style.minimalist': 'Minimalist',
    'style.realism': 'Realism',

    // Home Page
    'home.hero_title': 'Create Stunning Chinese Traditional Tattoos with AI',
    'home.hero_subtitle': 'AI-Powered Tattoo Design Platform',
    'home.hero_description': 'Transform your ideas into unique tattoo art in seconds. Powered by advanced AI technology.',
    'home.get_started': 'Get Started',
    'home.view_examples': 'View Examples',
    'home.features_title': 'Core Features',
    'home.featured_works': 'Featured Works',
    'home.view_all': 'View All',
    'home.cta_title': 'Ready to Start?',
    'home.cta_description': 'Join thousands of creators and discover your next tattoo inspiration.',
    'home.free_signup': 'Sign Up Free',
    'home.feature_ai_title': 'AI Generation',
    'home.feature_ai_desc': 'Generate unique tattoo designs with advanced AI',
    'home.feature_styles_title': 'Multiple Styles',
    'home.feature_styles_desc': 'Chinese, Japanese, American, and more',
    'home.feature_style_title': 'Traditional Styles',
    'home.feature_style_desc': 'Explore authentic Chinese traditional tattoo styles and cultural elements',
    'home.feature_community_title': 'Community',
    'home.feature_community_desc': 'Share and discover inspiration from others',
    'home.feature_artist_title': 'Professional Artists',
    'home.feature_artist_desc': 'Connect with certified tattoo artists for your next ink',
    'home.how_it_works': 'How It Works',
    'home.step1_title': 'Describe Your Vision',
    'home.step1_desc': 'Tell us what tattoo style and design you want',
    'home.step2_title': 'AI Generates',
    'home.step2_desc': 'Our AI creates unique designs based on your description',
    'home.step3_title': 'Download & Share',
    'home.step3_desc': 'Get high-quality designs ready for your tattoo artist',

    // Explore Page
    'explore.title': 'Community',
    'explore.recommend': 'For You',
    'explore.latest': 'Latest',
    'explore.hot': 'Popular',
    'explore.following': 'Following',
    'explore.search_placeholder': 'Search posts...',
    'explore.no_results': 'No posts found',
    'explore.load_more': 'Load More',
    'explore.trending_tags': 'Trending Tags',

    // Inspire Page
    'inspire.title': 'Inspiration',
    'inspire.subtitle': 'Get inspired by these traditional Chinese tattoo prompts',
    'inspire.copy_prompt': 'Copy Prompt',
    'inspire.copied': 'Copied!',

    // Pricing Page
    'pricing.title': 'Membership Plans',
    'pricing.subtitle': 'Choose the plan that works best for you',
    'pricing.current_plan': 'Current Plan',
    'pricing.features': 'Features',
    'pricing.unlimited_generations': 'Unlimited Generations',
    'pricing.priority_support': 'Priority Support',
    'pricing.exclusive_styles': 'Exclusive Styles',
    'pricing.choose_plan': 'Choose Plan',

    // Profile Page
    'profile.posts': 'Posts',
    'profile.saved': 'Saved',
    'profile.followers': 'Followers',
    'profile.following': 'Following',
    'profile.edit_profile': 'Edit Profile',
    'profile.follow': 'Follow',
    'profile.unfollow': 'Unfollow',
    'profile.no_posts': 'No posts yet',

    // Create Page
    'create.title': 'Create Post',
    'create.select_images': 'Select Images',
    'create.drag_or_click': 'Drag and drop images here or click to select',
    'create.post_type': 'Post Type',
    'create.work': 'Tattoo Work',
    'create.idea': 'Idea',
    'create.tattoo_style': 'Tattoo Style',
    'create.tags': 'Tags',
    'create.visibility': 'Visibility',
    'create.public': 'Public',
    'create.followers_only': 'Followers Only',
    'create.private': 'Private',
    'create.post': 'Post',
    'create.posting': 'Posting...',

    // Post Detail
    'post.likes': 'Likes',
    'post.comments': 'Comments',
    'post.share': 'Share',
    'post.report': 'Report',
    'post.write_comment': 'Write a comment...',
    'post.send': 'Send',
    'post.delete': 'Delete',
    'post.edit': 'Edit',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.mark_all_read': 'Mark all as read',
    'notifications.no_notifications': 'No notifications yet',
    'notifications.liked': 'liked your post',
    'notifications.commented': 'commented on your post',
    'notifications.followed': 'started following you',
    'notifications.save': 'saved your post',

    // Artist
    'artist.apply': 'Apply as Artist',
    'artist.portfolio': 'Portfolio',
    'artist.specialties': 'Specialties',
    'artist.experience': 'Experience',
    'artist.book_appointment': 'Book Appointment',
    'artist.view_profile': 'View Profile',

    // Common Actions
    'action.like': 'Like',
    'action.unlike': 'Unlike',
    'action.save': 'Save',
    'action.unsave': 'Unsave',
    'action.share': 'Share',
    'action.report': 'Report',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'action.follow': 'Follow',
    'action.unfollow': 'Unfollow',

    // Legal
    'legal.terms': 'Terms of Service',
    'legal.privacy': 'Privacy Policy',
    'legal.disclaimer': 'Disclaimer',
  },

  ja: {
    // Navigation
    'nav.home': 'ホーム',
    'nav.community': 'コミュニティ',
    'nav.inspire': 'インスピレーション',
    'nav.blog': 'ブログ',
    'nav.artists': 'アーティスト',
    'nav.upgrade': 'アップグレード',
    'nav.apply_artist': 'アーティスト申請',
    'nav.sign_in': 'ログイン',
    'nav.profile': 'プロフィール',
    'nav.notifications': '通知',
    'nav.post': '投稿',
    'nav.alerts': '通知',
    'nav.me': 'マイページ',
    
    // Home Page - Popular Styles
    'home.popular_styles': '人気のタトゥースタイル',
    'home.explore_all': 'すべて見る',
    'home.trending': 'トレンド',

    // AI Generator
    'ai.title': 'AI タトゥー ジェネレーター',
    'ai.subtitle': 'AI で素晴らしい中国伝統タトゥーデザインを作成',
    'ai.style': 'スタイル',
    'ai.body_part': 'ボディ部位',
    'ai.prompt_placeholder': 'タトゥーのアイデアを入力...',
    'ai.generate': '生成する',
    'ai.generating': '生成中...',
    'ai.sign_in_to_generate': 'ログインして生成',
    'ai.preview': 'プレビュー',
    'ai.download': 'HD ダウンロード',
    'ai.share': '共有',
    'ai.your_design': 'タトゥーデザインがここに表示されます',
    'ai.upload_image': '参照画像をアップロード',
    'ai.analyzing': '文化的意味を分析中...',

    // Pricing (basic)
    'pricing.free': 'フリー',
    'pricing.monthly': 'マンスリー',
    'pricing.yearly': 'イアーリー',
    'pricing.lifetime': 'ライフタイム',
    'pricing.per_day': '/日',
    'pricing.per_month': '/月',
    'pricing.per_year': '/年',
    'pricing.generations': '生成',
    'pricing.watermark': '透かし',
    'pricing.no_watermark': '透かしなし',
    'pricing.upgrade': 'アップグレード',

    // Common
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.save': '保存',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.close': '閉じる',

    // Body Parts
    'body.arm': '腕',
    'body.back': '背中',
    'body.chest': '胸',
    'body.wrist': '手首',
    'body.collarbone': '鎖骨',
    'body.thigh': '太もも',
    'body.calf': 'ふくらはぎ',

    // Auth - Login
    'auth.welcome_back': 'おかえりなさい',
    'auth.sign_in_to_continue': 'ログインして続行',
    'auth.sign_in': 'ログイン',
    'auth.signing_in': 'ログイン中...',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.enter_email': 'メールアドレスを入力',
    'auth.enter_password': 'パスワードを入力',
    'auth.no_account': 'アカウントをお持ちでない方',
    'auth.sign_up_link': '新規登録',
    'auth.forgot_password': 'パスワードをお忘れですか？',

    // Auth - Register
    'auth.create_account': 'アカウント作成',
    'auth.join_community': 'InkAI.life コミュニティに参加',
    'auth.username': 'ユーザー名',
    'auth.choose_username': 'ユーザー名を選択',
    'auth.create_password': 'パスワードを作成',
    'auth.creating': '作成中...',
    'auth.has_account': 'すでにアカウントをお持ちの方',
    'auth.sign_in_link': 'ログイン',
    'auth.agree_terms': '同意する',
        'auth.terms_of_service': '利用規約',
    'auth.sign_up': '新規登録',
    'auth.sign_in_required': 'ログインが必要です',
    'auth.sign_in_desc': '続行するにはログインしてください',
    'auth.login_to_post': '作品を共有するにはログイン',
    'auth.login_to_post_desc': 'タトゥー愛好家のコミュニティに参加',
    'auth.login_to_like': 'いいねするにはログイン',
    'auth.login_to_like_desc': '素晴らしい作品への感謝を示す',
    'auth.login_to_comment': 'コメントするにはログイン',
    'auth.login_to_comment_desc': 'コミュニティと意見を共有',
    'auth.login_to_generate': '作成するにはログイン',
    'auth.login_to_generate_desc': 'AIタトゥーデザインツールにアクセス',
    'auth.login_to_save': '保存するにはログイン',
    'auth.login_to_save_desc': 'お気に入りのデザインをブックマーク',
    'auth.login_to_follow': 'フォローするにはログイン',
    'auth.login_to_follow_desc': 'お気に入りのアーティストとつながる',
    'auth.confirm_email': 'メールを確認してください',
    'auth.go_to_signin': 'ログイン画面へ',

    // Styles
    'style.oriental': '中華風',
    'style.japanese': '和風',
    'style.american_traditional': 'アメリカントラディショナル',
    'style.neo_traditional': 'ネオトラディショナル',
    'style.blackwork': 'ダーク＆ブラックワーク',
    'style.watercolor': '水彩',
    'style.minimalist': 'ミニマリスト',
    'style.realism': 'リアリスム',

    // Home Page
    'home.hero_title': 'AIで中国の伝統タトゥーデザインを作成',
    'home.hero_subtitle': 'AI搭載タトゥーデザインプラットフォーム',
    'home.hero_description': 'あなたのアイデアを数秒でユニークなタトゥーアートに変換。先進的なAI技術搭載。',
    'home.get_started': '始める',
    'home.view_examples': '例を見る',
    'home.features_title': 'コア機能',
    'home.featured_works': '注目の作品',
    'home.view_all': 'すべて見る',
    'home.cta_title': '始める準備はできましたか？',
    'home.cta_description': '何千人ものクリエイターに参加して、次のタトゥーインスピレーションを見つけましょう。',
    'home.free_signup': '無料登録',
    'home.feature_ai_title': 'AI生成',
    'home.feature_ai_desc': '先進的なAIでユニークなタトゥーデザインを生成',
    'home.feature_styles_title': '複数のスタイル',
    'home.feature_styles_desc': '中華風、和風、アメリカンなど',
    'home.feature_style_title': '伝統的なスタイル',
    'home.feature_style_desc': '本物の中国伝統タトゥースタイルと文化要素を探索',
    'home.feature_community_title': 'コミュニティ',
    'home.feature_community_desc': '作品を共有し、他者からインスピレーションを得る',
    'home.feature_artist_title': 'プロフェッショナルアーティスト',
    'home.feature_artist_desc': '次のインクのために認定タトゥーアーティストとつながる',
    'home.how_it_works': '仕組み',
    'home.step1_title': 'あなたのビジョンを伝える',
    'home.step1_desc': 'タトゥースタイルとデザインを教えてください',
    'home.step2_title': 'AIが生成',
    'home.step2_desc': 'AIがあなたの説明に基づいてユニークなデザインを生成',
    'home.step3_title': 'ダウンロード＆共有',
    'home.step3_desc': 'タトゥーアーティスト用の高品質デザインを入手',

    // Explore Page
    'explore.title': 'コミュニティ',
    'explore.recommend': 'おすすめ',
    'explore.latest': '最新',
    'explore.hot': '人気',
    'explore.following': 'フォロー中',
    'explore.search_placeholder': '投稿を検索...',
    'explore.no_results': '投稿が見つかりません',
    'explore.load_more': 'もっと読み込む',
    'explore.trending_tags': 'トレンドタグ',

    // Inspire Page
    'inspire.title': 'インスピレーション',
    'inspire.subtitle': 'これらの伝統的な中国タトゥープロンプトからインスピレーションを得る',
    'inspire.copy_prompt': 'プロンプトをコピー',
    'inspire.copied': 'コピーしました！',

    // Pricing Page
    'pricing.title': 'メンバーシッププラン',
    'pricing.subtitle': 'あなたに最適なプランを選択',
    'pricing.current_plan': '現在のプラン',
    'pricing.features': '機能',
    'pricing.unlimited_generations': '無制限生成',
    'pricing.priority_support': '優先サポート',
    'pricing.exclusive_styles': '限定スタイル',
    'pricing.choose_plan': 'プランを選択',

    // Profile Page
    'profile.posts': '投稿',
    'profile.saved': '保存済み',
    'profile.followers': 'フォロワー',
    'profile.following': 'フォロー中',
    'profile.edit_profile': 'プロフィールを編集',
    'profile.follow': 'フォロー',
    'profile.unfollow': 'フォロー解除',
    'profile.no_posts': 'まだ投稿がありません',

    // Create Page
    'create.title': '投稿を作成',
    'create.select_images': '画像を選択',
    'create.drag_or_click': '画像をドラッグ＆ドロップするか、クリックして選択',
    'create.post_type': '投稿タイプ',
    'create.work': 'タトゥワーク',
    'create.idea': 'アイデア',
    'create.tattoo_style': 'タトゥースタイル',
    'create.tags': 'タグ',
    'create.visibility': '公開設定',
    'create.public': '公開',
    'create.followers_only': 'フォロワーのみ',
    'create.private': '非公開',
    'create.post': '投稿する',
    'create.posting': '投稿中...',

    // Post Detail
    'post.likes': 'いいね',
    'post.comments': 'コメント',
    'post.share': '共有',
    'post.report': '報告',
    'post.write_comment': 'コメントを書く...',
    'post.send': '送信',
    'post.delete': '削除',
    'post.edit': '編集',

    // Notifications
    'notifications.title': '通知',
    'notifications.mark_all_read': 'すべて既読にする',
    'notifications.no_notifications': '通知はまだありません',
    'notifications.liked': 'あなたの投稿をいいねしました',
    'notifications.commented': 'あなたの投稿にコメントしました',
    'notifications.followed': 'フォローしました',
    'notifications.save': 'あなたの投稿を保存しました',

    // Artist
    'artist.apply': 'アーティストとして申請',
    'artist.portfolio': 'ポートフォリオ',
    'artist.specialties': '専門分野',
    'artist.experience': '経験',
    'artist.book_appointment': '予約する',
    'artist.view_profile': 'プロフィールを見る',

    // Common Actions
    'action.like': 'いいね',
    'action.unlike': 'いいね解除',
    'action.save': '保存',
    'action.unsave': '保存解除',
    'action.share': '共有',
    'action.report': '報告',
    'action.delete': '削除',
    'action.edit': '編集',
    'action.follow': 'フォロー',
    'action.unfollow': 'フォロー解除',

    // Legal
    'legal.terms': '利用規約',
    'legal.privacy': 'プライバシーポリシー',
    'legal.disclaimer': '免責事項',
  },

  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.community': '社区',
    'nav.inspire': '灵感',
    'nav.blog': '博客',
    'nav.artists': '艺术家',
    'nav.upgrade': '升级',
    'nav.apply_artist': '申请艺术家',
    'nav.sign_in': '登录',
    'nav.profile': '个人资料',
    'nav.notifications': '通知',
    'nav.post': '发布',
    'nav.alerts': '消息',
    'nav.me': '我的',
    
    // Home Page - Popular Styles
    'home.popular_styles': '热门纹身风格',
    'home.explore_all': '查看全部',
    'home.trending': '热门',

    // AI Generator
    'ai.title': 'AI 纹身生成器',
    'ai.subtitle': '用 AI 创作精美的中式传统纹身设计',
    'ai.style': '风格',
    'ai.body_part': '纹身部位',
    'ai.prompt_placeholder': '描述你的纹身想法...',
    'ai.generate': '生成纹身',
    'ai.generating': '生成中...',
    'ai.sign_in_to_generate': '登录以生成',
    'ai.preview': '预览',
    'ai.download': '下载高清',
    'ai.share': '分享',
    'ai.your_design': '你的纹身设计将显示在这里',
    'ai.upload_image': '上传参考图片',
    'ai.analyzing': '正在分析文化含义...',

    // Pricing (basic)
    'pricing.free': '免费',
    'pricing.monthly': '月付',
    'pricing.yearly': '年付',
    'pricing.lifetime': '终身',
    'pricing.per_day': '/天',
    'pricing.per_month': '/月',
    'pricing.per_year': '/年',
    'pricing.generations': '次生成',
    'pricing.watermark': '水印',
    'pricing.no_watermark': '无水印',
    'pricing.upgrade': '立即升级',

    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.close': '关闭',

    // Body Parts
    'body.arm': '手臂',
    'body.back': '背部',
    'body.chest': '胸部',
    'body.wrist': '手腕',
    'body.collarbone': '锁骨',
    'body.thigh': '大腿',
    'body.calf': '小腿',

    // Auth - Login
    'auth.welcome_back': '欢迎回来',
    'auth.sign_in_to_continue': '登录以继续您的旅程',
    'auth.sign_in': '登录',
    'auth.signing_in': '登录中...',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.enter_email': '输入您的邮箱',
    'auth.enter_password': '输入您的密码',
    'auth.no_account': '还没有账户？',
    'auth.sign_up_link': '立即注册',
    'auth.forgot_password': '忘记密码？',

    // Auth - Register
    'auth.create_account': '创建账户',
    'auth.join_community': '加入 InkAI.life 社区',
    'auth.username': '用户名',
    'auth.choose_username': '选择用户名',
    'auth.create_password': '创建密码',
    'auth.creating': '创建中...',
    'auth.has_account': '已有账户？',
    'auth.sign_in_link': '立即登录',
    'auth.agree_terms': '我同意',
    'auth.terms_of_service': '服务条款',

    // Styles
    'style.oriental': '中式',
    'style.japanese': '日式',
    'style.american_traditional': '美式传统',
    'style.neo_traditional': '新传统',
    'style.blackwork': '暗黑黑灰',
    'style.watercolor': '水彩',
    'style.minimalist': '极简线条',
    'style.realism': '写实',

    // Home Page
    'home.hero_title': '用 AI 创作惊艳的中式传统纹身',
    'home.hero_subtitle': 'AI 驱动的纹身设计平台',
    'home.hero_description': '将你的想法转化为独特的纹身艺术，仅需数秒。由先进 AI 技术驱动。',
    'home.get_started': '开始创作',
    'home.view_examples': '浏览作品',
    'home.features_title': '核心功能',
    'home.featured_works': '精选作品',
    'home.view_all': '查看全部',
    'home.cta_title': '准备好开始了吗？',
    'home.cta_description': '加入数千名创作者，发现你的下一个纹身灵感。',
    'home.free_signup': '免费注册',
    'home.feature_ai_title': 'AI 生成',
    'home.feature_ai_desc': '使用先进 AI 生成独特纹身设计',
    'home.feature_styles_title': '多种风格',
    'home.feature_styles_desc': '中式、日式、美式等多种选择',
    'home.feature_style_title': '传统风格',
    'home.feature_style_desc': '探索正宗的中式传统纹身风格和文化元素',
    'home.feature_community_title': '社区分享',
    'home.feature_community_desc': '分享作品，发现他人灵感',
    'home.feature_artist_title': '专业艺术家',
    'home.feature_artist_desc': '与认证纹身艺术家联系，完成您的下一个纹身',
    'home.how_it_works': '使用方法',
    'home.step1_title': '描述您的想法',
    'home.step1_desc': '告诉我们您想要的纹身风格和设计',
    'home.step2_title': 'AI 生成',
    'home.step2_desc': '我们的 AI 根据您的描述创建独特的设计',
    'home.step3_title': '下载和分享',
    'home.step3_desc': '获取适合纹身艺术家的高品质设计',

    // Explore Page
    'explore.title': '社区',
    'explore.recommend': '推荐',
    'explore.latest': '最新',
    'explore.hot': '热门',
    'explore.following': '关注中',
    'explore.search_placeholder': '搜索帖子...',
    'explore.no_results': '未找到帖子',
    'explore.load_more': '加载更多',
    'explore.trending_tags': '热门标签',

    // Inspire Page
    'inspire.title': '灵感',
    'inspire.subtitle': '从这些传统中式纹身提示中获取灵感',
    'inspire.copy_prompt': '复制提示',
    'inspire.copied': '已复制！',

    // Pricing Page
    'pricing.title': '会员计划',
    'pricing.subtitle': '选择最适合您的方案',
    'pricing.current_plan': '当前方案',
    'pricing.features': '功能',
    'pricing.unlimited_generations': '无限生成',
    'pricing.priority_support': '优先支持',
    'pricing.exclusive_styles': '专属风格',
    'pricing.choose_plan': '选择方案',

    // Profile Page
    'profile.posts': '帖子',
    'profile.saved': '已保存',
    'profile.followers': '粉丝',
    'profile.following': '关注中',
    'profile.edit_profile': '编辑资料',
    'profile.follow': '关注',
    'profile.unfollow': '取消关注',
    'profile.no_posts': '还没有帖子',

    // Create Page
    'create.title': '创建帖子',
    'create.select_images': '选择图片',
    'create.drag_or_click': '拖拽图片到此处或点击选择',
    'create.post_type': '帖子类型',
    'create.work': '纹身作品',
    'create.idea': '创意',
    'create.tattoo_style': '纹身风格',
    'create.tags': '标签',
    'create.visibility': '可见性',
    'create.public': '公开',
    'create.followers_only': '仅关注者',
    'create.private': '私密',
    'create.post': '发布',
    'create.posting': '发布中...',

    // Post Detail
    'post.likes': '点赞',
    'post.comments': '评论',
    'post.share': '分享',
    'post.report': '举报',
    'post.write_comment': '写评论...',
    'post.send': '发送',
    'post.delete': '删除',
    'post.edit': '编辑',

    // Notifications
    'notifications.title': '通知',
    'notifications.mark_all_read': '全部标记为已读',
    'notifications.no_notifications': '暂无通知',
    'notifications.liked': '赞了你的帖子',
    'notifications.commented': '评论了你的帖子',
    'notifications.followed': '关注了你',
    'notifications.save': '保存了你的帖子',

    // Artist
    'artist.apply': '申请成为艺术家',
    'artist.portfolio': '作品集',
    'artist.specialties': '专长',
    'artist.experience': '经验',
    'artist.book_appointment': '预约',
    'artist.view_profile': '查看资料',

    // Common Actions
    'action.like': '点赞',
    'action.unlike': '取消点赞',
    'action.save': '保存',
    'action.unsave': '取消保存',
    'action.share': '分享',
    'action.report': '举报',
    'action.delete': '删除',
    'action.edit': '编辑',
    'action.follow': '关注',
    'action.unfollow': '取消关注',

    // Legal
    'legal.terms': '服务条款',
    'legal.privacy': '隐私政策',
    'legal.disclaimer': '免责声明',
  },

  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.community': 'Comunidade',
    'nav.inspire': 'Inspiração',
    'nav.blog': 'Blog',
    'nav.artists': 'Artistas',
    'nav.upgrade': 'Upgrade',
    'nav.apply_artist': 'Aplicar Artista',
    'nav.sign_in': 'Entrar',
    'nav.profile': 'Perfil',
    'nav.notifications': 'Notificações',
    'nav.post': 'Postar',
    'nav.alerts': 'Alertas',
    'nav.me': 'Eu',
    
    // Home Page - Popular Styles
    'home.popular_styles': 'Estilos Populares',
    'home.explore_all': 'Explorar Tudo',
    'home.trending': 'Em Alta',

    // AI Generator
    'ai.title': 'Gerador de Tatuagem AI',
    'ai.subtitle': 'Crie designs de tatuagens tradicionais chinesas impressionantes com IA',
    'ai.style': 'Estilo',
    'ai.body_part': 'Parte do Corpo',
    'ai.prompt_placeholder': 'Descreva sua ideia de tatuagem...',
    'ai.generate': 'Gerar Tatuagem',
    'ai.generating': 'Gerando...',
    'ai.sign_in_to_generate': 'Entre para Gerar',
    'ai.preview': 'Visualização',
    'ai.download': 'Baixar HD',
    'ai.share': 'Compartilhar',
    'ai.your_design': 'Seu design de tatuagem aparecerá aqui',
    'ai.upload_image': 'Carregar imagem de referência',
    'ai.analyzing': 'Analisando significado cultural...',

    // Pricing (basic)
    'pricing.free': 'Grátis',
    'pricing.monthly': 'Mensal',
    'pricing.yearly': 'Anual',
    'pricing.lifetime': 'Vitalício',
    'pricing.per_day': '/dia',
    'pricing.per_month': '/mês',
    'pricing.per_year': '/ano',
    'pricing.generations': 'gerações',
    'pricing.watermark': 'Marca d\'água',
    'pricing.no_watermark': 'Sem Marca d\'água',
    'pricing.upgrade': 'Atualizar Agora',

    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Salvar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.close': 'Fechar',

    // Body Parts
    'body.arm': 'Braço',
    'body.back': 'Costas',
    'body.chest': 'Peito',
    'body.wrist': 'Pulso',
    'body.collarbone': 'Clavícula',
    'body.thigh': 'Coxa',
    'body.calf': 'Panturrilha',

    // Auth - Login
    'auth.welcome_back': 'Bem-vindo de Volta',
    'auth.sign_in_to_continue': 'Entre para continuar sua jornada',
    'auth.sign_in': 'Entrar',
    'auth.signing_in': 'Entrando...',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.enter_email': 'Digite seu e-mail',
    'auth.enter_password': 'Digite sua senha',
    'auth.no_account': 'Não tem uma conta?',
    'auth.sign_up_link': 'Cadastre-se',
    'auth.forgot_password': 'Esqueceu a senha?',

    // Auth - Register
    'auth.create_account': 'Criar Conta',
    'auth.join_community': 'Junte-se à comunidade InkAI.life',
    'auth.username': 'Nome de Usuário',
    'auth.choose_username': 'Escolha um nome de usuário',
    'auth.create_password': 'Crie uma senha',
    'auth.creating': 'Criando...',
    'auth.has_account': 'Já tem uma conta?',
    'auth.sign_in_link': 'Entrar',
    'auth.agree_terms': 'Eu concordo com o',
        'auth.terms_of_service': 'Termos de Serviço',
    'auth.sign_up': 'Cadastrar',
    'auth.sign_in_required': 'Login necessário',
    'auth.sign_in_desc': 'Por favor, faça login para continuar',
    'auth.login_to_post': 'Entre para compartilhar seu trabalho',
    'auth.login_to_post_desc': 'Junte-se à nossa comunidade de entusiastas de tatuagem',
    'auth.login_to_like': 'Entre para curtir',
    'auth.login_to_like_desc': 'Mostre sua apreciação por arte incrível',
    'auth.login_to_comment': 'Entre para comentar',
    'auth.login_to_comment_desc': 'Compartilhe seus pensamentos com a comunidade',
    'auth.login_to_generate': 'Entre para criar',
    'auth.login_to_generate_desc': 'Acesse ferramentas de design de tatuagem com IA',
    'auth.login_to_save': 'Entre para salvar',
    'auth.login_to_save_desc': 'Salve seus designs favoritos',
    'auth.login_to_follow': 'Entre para seguir',
    'auth.login_to_follow_desc': 'Conecte-se com seus artistas favoritos',
    'auth.confirm_email': 'Verifique seu email',
    'auth.go_to_signin': 'Ir para Login',

    // Styles
    'style.oriental': 'Oriental',
    'style.japanese': 'Japonês',
    'style.american_traditional': 'Americano Tradicional',
    'style.neo_traditional': 'Neo Tradicional',
    'style.blackwork': 'Escuro & Blackwork',
    'style.watercolor': 'Aquarela',
    'style.minimalist': 'Minimalista',
    'style.realism': 'Realismo',

    // Home Page
    'home.hero_title': 'Crie Tatuagens Tradicionais Chinesas Incríveis com IA',
    'home.hero_subtitle': 'Transforme suas ideias em designs de tatuagem únicos em segundos. Alimentado por tecnologia avançada de IA.',
    'home.get_started': 'Comece Grátis',
    'home.view_examples': 'Ver Exemplos',
    'home.features_title': 'Por Que Escolher a InkAI',
    'home.feature_ai_title': 'Design com IA',
    'home.feature_ai_desc': 'Gere designs de tatuagem únicos instantaneamente com nossa IA avançada',
    'home.feature_style_title': 'Estilos Tradicionais',
    'home.feature_style_desc': 'Explore estilos autênticos de tatuagem tradicional chinesa e elementos culturais',
    'home.feature_community_title': 'Galeria da Comunidade',
    'home.feature_community_desc': 'Compartilhe seus designs e descubra inspiração da nossa comunidade',
    'home.feature_artist_title': 'Artistas Profissionais',
    'home.feature_artist_desc': 'Conecte-se com tatuadores certificados para sua próxima tatuagem',
    'home.how_it_works': 'Como Funciona',
    'home.step1_title': 'Descreva Sua Visão',
    'home.step1_desc': 'Nos diga qual estilo e design de tatuagem você deseja',
    'home.step2_title': 'IA Gera',
    'home.step2_desc': 'Nossa IA cria designs únicos com base na sua descrição',
    'home.step3_title': 'Baixar & Compartilhar',
    'home.step3_desc': 'Obtenha designs de alta qualidade prontos para seu tatuador',

    // Explore Page
    'explore.title': 'Comunidade',
    'explore.recommend': 'Para Você',
    'explore.latest': 'Recentes',
    'explore.hot': 'Popular',
    'explore.following': 'Seguindo',
    'explore.search_placeholder': 'Buscar publicações...',
    'explore.no_results': 'Nenhuma publicação encontrada',
    'explore.load_more': 'Carregar Mais',
    'explore.trending_tags': 'Tags em Alta',

    // Inspire Page
    'inspire.title': 'Inspiração',
    'inspire.subtitle': 'Inspire-se com essas sugestões de tatuagem tradicional chinesa',
    'inspire.copy_prompt': 'Copiar Sugestão',
    'inspire.copied': 'Copiado!',

    // Pricing Page
    'pricing.title': 'Planos de Assinatura',
    'pricing.subtitle': 'Escolha o plano que melhor funciona para você',
    'pricing.current_plan': 'Plano Atual',
    'pricing.features': 'Recursos',
    'pricing.unlimited_generations': 'Gerações Ilimitadas',
    'pricing.priority_support': 'Suporte Prioritário',
    'pricing.exclusive_styles': 'Estilos Exclusivos',
    'pricing.choose_plan': 'Escolher Plano',

    // Profile Page
    'profile.posts': 'Publicações',
    'profile.saved': 'Salvos',
    'profile.followers': 'Seguidores',
    'profile.following': 'Seguindo',
    'profile.edit_profile': 'Editar Perfil',
    'profile.follow': 'Seguir',
    'profile.unfollow': 'Deixar de Seguir',
    'profile.no_posts': 'Nenhuma publicação ainda',

    // Create Page
    'create.title': 'Criar Publicação',
    'create.select_images': 'Selecionar Imagens',
    'create.drag_or_click': 'Arraste e solte imagens aqui ou clique para selecionar',
    'create.post_type': 'Tipo de Publicação',
    'create.work': 'Trabalho de Tatuagem',
    'create.idea': 'Ideia',
    'create.tattoo_style': 'Estilo de Tatuagem',
    'create.tags': 'Tags',
    'create.visibility': 'Visibilidade',
    'create.public': 'Público',
    'create.followers_only': 'Apenas Seguidores',
    'create.private': 'Privado',
    'create.post': 'Publicar',
    'create.posting': 'Publicando...',

    // Post Detail
    'post.likes': 'Curtidas',
    'post.comments': 'Comentários',
    'post.share': 'Compartilhar',
    'post.report': 'Denunciar',
    'post.write_comment': 'Escreva um comentário...',
    'post.send': 'Enviar',
    'post.delete': 'Excluir',
    'post.edit': 'Editar',

    // Notifications
    'notifications.title': 'Notificações',
    'notifications.mark_all_read': 'Marcar todas como lidas',
    'notifications.no_notifications': 'Nenhuma notificação ainda',
    'notifications.liked': 'curtiu sua publicação',
    'notifications.commented': 'comentou na sua publicação',
    'notifications.followed': 'começou a seguir você',
    'notifications.save': 'salvou sua publicação',

    // Artist
    'artist.apply': 'Candidate-se como Artista',
    'artist.portfolio': 'Portfólio',
    'artist.specialties': 'Especialidades',
    'artist.experience': 'Experiência',
    'artist.book_appointment': 'Agendar Horário',
    'artist.view_profile': 'Ver Perfil',

    // Common Actions
    'action.like': 'Curtir',
    'action.unlike': 'Descurtir',
    'action.save': 'Salvar',
    'action.unsave': 'Remover dos Salvos',
    'action.share': 'Compartilhar',
    'action.report': 'Denunciar',
    'action.delete': 'Excluir',
    'action.edit': 'Editar',
    'action.follow': 'Seguir',
    'action.unfollow': 'Deixar de Seguir',

    // Legal
    'legal.terms': 'Termos de Serviço',
    'legal.privacy': 'Política de Privacidade',
    'legal.disclaimer': 'Aviso Legal',
  },

  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.community': 'Comunidad',
    'nav.inspire': 'Inspiración',
    'nav.blog': 'Blog',
    'nav.artists': 'Artistas',
    'nav.upgrade': 'Mejorar',
    'nav.apply_artist': 'Aplicar Artista',
    'nav.sign_in': 'Iniciar Sesión',
    'nav.profile': 'Perfil',
    'nav.notifications': 'Notificaciones',
    'nav.post': 'Publicar',
    'nav.alerts': 'Alertas',
    'nav.me': 'Yo',
    
    // Home Page - Popular Styles
    'home.popular_styles': 'Estilos Populares',
    'home.explore_all': 'Explorar Todo',
    'home.trending': 'Tendencias',

    // AI Generator
    'ai.title': 'Generador de Tatuajes AI',
    'ai.subtitle': 'Crea impresionantes diseños de tatuajes tradicionales chinos con IA',
    'ai.style': 'Estilo',
    'ai.body_part': 'Parte del Cuerpo',
    'ai.prompt_placeholder': 'Describe tu idea de tatuaje...',
    'ai.generate': 'Generar Tatuaje',
    'ai.generating': 'Generando...',
    'ai.sign_in_to_generate': 'Inicia sesión para Generar',
    'ai.preview': 'Vista Previa',
    'ai.download': 'Descargar HD',
    'ai.share': 'Compartir',
    'ai.your_design': 'Tu diseño de tatuaje aparecerá aquí',
    'ai.upload_image': 'Subir imagen de referencia',
    'ai.analyzing': 'Analizando significado cultural...',

    // Pricing (basic)
    'pricing.free': 'Gratis',
    'pricing.monthly': 'Mensual',
    'pricing.yearly': 'Anual',
    'pricing.lifetime': 'Vitalicio',
    'pricing.per_day': '/día',
    'pricing.per_month': '/mes',
    'pricing.per_year': '/año',
    'pricing.generations': 'generaciones',
    'pricing.watermark': 'Marca de agua',
    'pricing.no_watermark': 'Sin Marca de agua',
    'pricing.upgrade': 'Mejorar Ahora',

    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',

    // Body Parts
    'body.arm': 'Brazo',
    'body.back': 'Espalda',
    'body.chest': 'Pecho',
    'body.wrist': 'Muñeca',
    'body.collarbone': 'Clavícula',
    'body.thigh': 'Muslo',
    'body.calf': 'Pantorrilla',

    // Auth - Login
    'auth.welcome_back': 'Bienvenido de Nuevo',
    'auth.sign_in_to_continue': 'Inicia sesión para continuar tu viaje',
    'auth.sign_in': 'Iniciar Sesión',
    'auth.signing_in': 'Iniciando sesión...',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.enter_email': 'Ingresa tu correo electrónico',
    'auth.enter_password': 'Ingresa tu contraseña',
    'auth.no_account': '¿No tienes una cuenta?',
    'auth.sign_up_link': 'Regístrate',
    'auth.forgot_password': '¿Olvidaste tu contraseña?',

    // Auth - Register
    'auth.create_account': 'Crear Cuenta',
    'auth.join_community': 'Únete a la comunidad InkAI.life',
    'auth.username': 'Nombre de Usuario',
    'auth.choose_username': 'Elige un nombre de usuario',
    'auth.create_password': 'Crea una contraseña',
    'auth.creating': 'Creando...',
    'auth.has_account': '¿Ya tienes una cuenta?',
    'auth.sign_in_link': 'Inicia sesión',
    'auth.agree_terms': 'Acepto los',
        'auth.terms_of_service': 'Términos de Servicio',
    'auth.sign_up': 'Registrarse',
    'auth.sign_in_required': 'Inicio de sesión requerido',
    'auth.sign_in_desc': 'Por favor, inicie sesión para continuar',
    'auth.login_to_post': 'Inicie sesión para compartir su trabajo',
    'auth.login_to_post_desc': 'Únase a nuestra comunidad de entusiastas del tatuaje',
    'auth.login_to_like': 'Inicie sesión para dar me gusta',
    'auth.login_to_like_desc': 'Muestre su apreciación por el arte increíble',
    'auth.login_to_comment': 'Inicie sesión para comentar',
    'auth.login_to_comment_desc': 'Comparta sus pensamientos con la comunidad',
    'auth.login_to_generate': 'Inicie sesión para crear',
    'auth.login_to_generate_desc': 'Acceda a herramientas de diseño de tatuajes con IA',
    'auth.login_to_save': 'Inicie sesión para guardar',
    'auth.login_to_save_desc': 'Guarde sus diseños favoritos',
    'auth.login_to_follow': 'Inicie sesión para seguir',
    'auth.login_to_follow_desc': 'Conéctese con sus artistas favoritos',
    'auth.confirm_email': 'Revise su email',
    'auth.go_to_signin': 'Ir a Iniciar Sesión',

    // Styles
    'style.oriental': 'Oriental',
    'style.japanese': 'Japonés',
    'style.american_traditional': 'Americano Tradicional',
    'style.neo_traditional': 'Neo Tradicional',
    'style.blackwork': 'Oscuro & Blackwork',
    'style.watercolor': 'Acuarela',
    'style.minimalist': 'Minimalista',
    'style.realism': 'Realismo',

    // Home Page
    'home.hero_title': 'Crea Impresionantes Tatuajes Tradicionales Chinos con IA',
    'home.hero_subtitle': 'Transforma tus ideas en diseños de tatuaje únicos en segundos. Impulsado por tecnología de IA avanzada.',
    'home.get_started': 'Comienza Gratis',
    'home.view_examples': 'Ver Ejemplos',
    'home.features_title': 'Por Qué Elegir InkAI',
    'home.feature_ai_title': 'Diseño con IA',
    'home.feature_ai_desc': 'Genera diseños de tatuaje únicos instantáneamente con nuestra IA avanzada',
    'home.feature_style_title': 'Estilos Tradicionales',
    'home.feature_style_desc': 'Explora estilos auténticos de tatuaje tradicional chino y elementos culturales',
    'home.feature_community_title': 'Galería de la Comunidad',
    'home.feature_community_desc': 'Comparte tus diseños y descubre inspiración de nuestra comunidad',
    'home.feature_artist_title': 'Artistas Profesionales',
    'home.feature_artist_desc': 'Conéctate con artistas del tatuaje certificados para tu próxima tinta',
    'home.how_it_works': 'Cómo Funciona',
    'home.step1_title': 'Describe Tu Visión',
    'home.step1_desc': 'Cuéntanos qué estilo y diseño de tatuaje quieres',
    'home.step2_title': 'IA Genera',
    'home.step2_desc': 'Nuestra IA crea diseños únicos basados en tu descripción',
    'home.step3_title': 'Descargar y Compartir',
    'home.step3_desc': 'Obtén diseños de alta calidad listos para tu artista del tatuaje',

    // Explore Page
    'explore.title': 'Comunidad',
    'explore.recommend': 'Para Ti',
    'explore.latest': 'Recientes',
    'explore.hot': 'Popular',
    'explore.following': 'Siguiendo',
    'explore.search_placeholder': 'Buscar publicaciones...',
    'explore.no_results': 'No se encontraron publicaciones',
    'explore.load_more': 'Cargar Más',
    'explore.trending_tags': 'Etiquetas Tendientes',

    // Inspire Page
    'inspire.title': 'Inspiración',
    'inspire.subtitle': 'Inspírate con estas ideas de tatuajes tradicionales chinos',
    'inspire.copy_prompt': 'Copiar Idea',
    'inspire.copied': '¡Copiado!',

    // Pricing Page
    'pricing.title': 'Planes de Membresía',
    'pricing.subtitle': 'Elige el plan que mejor funcione para ti',
    'pricing.current_plan': 'Plan Actual',
    'pricing.features': 'Características',
    'pricing.unlimited_generations': 'Generaciones Ilimitadas',
    'pricing.priority_support': 'Soporte Prioritario',
    'pricing.exclusive_styles': 'Estilos Exclusivos',
    'pricing.choose_plan': 'Elegir Plan',

    // Profile Page
    'profile.posts': 'Publicaciones',
    'profile.saved': 'Guardados',
    'profile.followers': 'Seguidores',
    'profile.following': 'Siguiendo',
    'profile.edit_profile': 'Editar Perfil',
    'profile.follow': 'Seguir',
    'profile.unfollow': 'Dejar de Seguir',
    'profile.no_posts': 'Sin publicaciones aún',

    // Create Page
    'create.title': 'Crear Publicación',
    'create.select_images': 'Seleccionar Imágenes',
    'create.drag_or_click': 'Arrastra y suelta imágenes aquí o haz clic para seleccionar',
    'create.post_type': 'Tipo de Publicación',
    'create.work': 'Trabajo de Tatuaje',
    'create.idea': 'Idea',
    'create.tattoo_style': 'Estilo de Tatuaje',
    'create.tags': 'Etiquetas',
    'create.visibility': 'Visibilidad',
    'create.public': 'Público',
    'create.followers_only': 'Solo Seguidores',
    'create.private': 'Privado',
    'create.post': 'Publicar',
    'create.posting': 'Publicando...',

    // Post Detail
    'post.likes': 'Me Gusta',
    'post.comments': 'Comentarios',
    'post.share': 'Compartir',
    'post.report': 'Reportar',
    'post.write_comment': 'Escribe un comentario...',
    'post.send': 'Enviar',
    'post.delete': 'Eliminar',
    'post.edit': 'Editar',

    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.mark_all_read': 'Marcar todas como leídas',
    'notifications.no_notifications': 'Sin notificaciones aún',
    'notifications.liked': 'le dio me gusta a tu publicación',
    'notifications.commented': 'comentó en tu publicación',
    'notifications.followed': 'empezó a seguirte',
    'notifications.save': 'guardó tu publicación',

    // Artist
    'artist.apply': 'Aplicar como Artista',
    'artist.portfolio': 'Portafolio',
    'artist.specialties': 'Especialidades',
    'artist.experience': 'Experiencia',
    'artist.book_appointment': 'Reservar Cita',
    'artist.view_profile': 'Ver Perfil',

    // Common Actions
    'action.like': 'Me Gusta',
    'action.unlike': 'Quitar Me Gusta',
    'action.save': 'Guardar',
    'action.unsave': 'Quitar de Guardados',
    'action.share': 'Compartir',
    'action.report': 'Reportar',
    'action.delete': 'Eliminar',
    'action.edit': 'Editar',
    'action.follow': 'Seguir',
    'action.unfollow': 'Dejar de Seguir',

    // Legal
    'legal.terms': 'Términos de Servicio',
    'legal.privacy': 'Política de Privacidad',
    'legal.disclaimer': 'Aviso Legal',
  },

  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.community': 'Gemeinschaft',
    'nav.inspire': 'Inspiration',
    'nav.blog': 'Blog',
    'nav.artists': 'Künstler',
    'nav.upgrade': 'Upgrade',
    'nav.apply_artist': 'Künstler Bewerben',
    'nav.sign_in': 'Anmelden',
    'nav.profile': 'Profil',
    'nav.notifications': 'Benachrichtigungen',
    'nav.post': 'Posten',
    'nav.alerts': 'Alerts',
    'nav.me': 'Ich',
    
    // Home Page - Popular Styles
    'home.popular_styles': 'Beliebte Tattoo-Stile',
    'home.explore_all': 'Alle Erkunden',
    'home.trending': 'Trending',

    // AI Generator
    'ai.title': 'AI Tattoo Generator',
    'ai.subtitle': 'Erstelle atemberaubende chinesische traditionelle Tattoo-Designs mit KI',
    'ai.style': 'Stil',
    'ai.body_part': 'Körperteil',
    'ai.prompt_placeholder': 'Beschreibe deine Tattoo-Idee...',
    'ai.generate': 'Tattoo Erstellen',
    'ai.generating': 'Wird erstellt...',
    'ai.sign_in_to_generate': 'Anmelden zum Erstellen',
    'ai.preview': 'Vorschau',
    'ai.download': 'HD Herunterladen',
    'ai.share': 'Teilen',
    'ai.your_design': 'Dein Tattoo-Design erscheint hier',
    'ai.upload_image': 'Referenzbild hochladen',
    'ai.analyzing': 'Kulturelle Bedeutung analysieren...',

    // Pricing (basic)
    'pricing.free': 'Kostenlos',
    'pricing.monthly': 'Monatlich',
    'pricing.yearly': 'Jährlich',
    'pricing.lifetime': 'Lebenslang',
    'pricing.per_day': '/Tag',
    'pricing.per_month': '/Monat',
    'pricing.per_year': '/Jahr',
    'pricing.generations': 'Generationen',
    'pricing.watermark': 'Wasserzeichen',
    'pricing.no_watermark': 'Kein Wasserzeichen',
    'pricing.upgrade': 'Jetzt Upgraden',

    // Common
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',

    // Body Parts
    'body.arm': 'Arm',
    'body.back': 'Rücken',
    'body.chest': 'Brust',
    'body.wrist': 'Handgelenk',
    'body.collarbone': 'Schlüsselbein',
    'body.thigh': 'Oberschenkel',
    'body.calf': 'Wade',

    // Auth - Login
    'auth.welcome_back': 'Willkommen Zurück',
    'auth.sign_in_to_continue': 'Melde dich an um fortzufahren',
    'auth.sign_in': 'Anmelden',
    'auth.signing_in': 'Anmelden...',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.enter_email': 'Gib deine E-Mail ein',
    'auth.enter_password': 'Gib dein Passwort ein',
    'auth.no_account': 'Noch kein Konto?',
    'auth.sign_up_link': 'Registrieren',
    'auth.forgot_password': 'Passwort vergessen?',

    // Auth - Register
    'auth.create_account': 'Konto Erstellen',
    'auth.join_community': 'Werde Teil der InkAI.life Community',
    'auth.username': 'Benutzername',
    'auth.choose_username': 'Wähle einen Benutzernamen',
    'auth.create_password': 'Erstelle ein Passwort',
    'auth.creating': 'Wird erstellt...',
    'auth.has_account': 'Bereits ein Konto?',
    'auth.sign_in_link': 'Anmelden',
    'auth.agree_terms': 'Ich stimme den',
        'auth.terms_of_service': 'Nutzungsbedingungen zu',
    'auth.sign_up': 'Registrieren',
    'auth.sign_in_required': 'Anmeldung erforderlich',
    'auth.sign_in_desc': 'Bitte melden Sie sich an, um fortzufahren',
    'auth.login_to_post': 'Melden Sie sich an, um Ihre Arbeit zu teilen',
    'auth.login_to_post_desc': 'Treten Sie unserer Community von Tattoo-Enthusiasten bei',
    'auth.login_to_like': 'Melden Sie sich an, um zu liken',
    'auth.login_to_like_desc': 'Zeigen Sie Ihre Wertschätzung für erstaunliche Kunstwerke',
    'auth.login_to_comment': 'Melden Sie sich an, um zu kommentieren',
    'auth.login_to_comment_desc': 'Teilen Sie Ihre Gedanken mit der Community',
    'auth.login_to_generate': 'Melden Sie sich an, um zu erstellen',
    'auth.login_to_generate_desc': 'Greifen Sie auf KI-gestützte Tattoo-Design-Tools zu',
    'auth.login_to_save': 'Melden Sie sich an, um zu speichern',
    'auth.login_to_save_desc': 'Speichern Sie Ihre Lieblingsdesigns',
    'auth.login_to_follow': 'Melden Sie sich an, um zu folgen',
    'auth.login_to_follow_desc': 'Verbinden Sie sich mit Ihren Lieblingskünstlern',
    'auth.confirm_email': 'Überprüfen Sie Ihre E-Mail',
    'auth.go_to_signin': 'Zur Anmeldung',

    // Styles
    'style.oriental': 'Orientalisch',
    'style.japanese': 'Japanisch',
    'style.american_traditional': 'Amerikanisch Traditionell',
    'style.neo_traditional': 'Neo Traditionell',
    'style.blackwork': 'Dunkel & Blackwork',
    'style.watercolor': 'Aquarell',
    'style.minimalist': 'Minimalistisch',
    'style.realism': 'Realismus',

    // Home Page
    'home.hero_title': 'Erstelle Atemberaubende Chinesische Traditionelle Tattoos mit KI',
    'home.hero_subtitle': 'Verwandle deine Ideen in Sekunden in einzigartige Tattoo-Designs. Angetrieben von fortschrittlicher KI-Technologie.',
    'home.get_started': 'Kostenlos Starten',
    'home.view_examples': 'Beispiele Ansehen',
    'home.features_title': 'Warum InkAI Wählen',
    'home.feature_ai_title': 'KI-gestütztes Design',
    'home.feature_ai_desc': 'Generiere sofort einzigartige Tattoo-Designs mit unserer fortschrittlichen KI-Technologie',
    'home.feature_style_title': 'Traditionelle Stile',
    'home.feature_style_desc': 'Entdecke authentische chinesische traditionelle Tattoo-Stile und kulturelle Elemente',
    'home.feature_community_title': 'Community-Galerie',
    'home.feature_community_desc': 'Teile deine Designs und finde Inspiration in unserer Community',
    'home.feature_artist_title': 'Professionelle Künstler',
    'home.feature_artist_desc': 'Verbinde dich mit zertifizierten Tattoo-Künstlern für dein nächstes Tattoo',
    'home.how_it_works': 'So Funktioniert\'s',
    'home.step1_title': 'Beschreibe Deine Vision',
    'home.step1_desc': 'Sag uns, welchen Tattoo-Stil und welches Design du möchtest',
    'home.step2_title': 'KI Generiert',
    'home.step2_desc': 'Unsere KI erstellt einzigartige Designs basierend auf deiner Beschreibung',
    'home.step3_title': 'Download & Teilen',
    'home.step3_desc': 'Erhalte hochwertige Designs bereit für deinen Tattoo-Künstler',

    // Explore Page
    'explore.title': 'Gemeinschaft',
    'explore.recommend': 'Für Dich',
    'explore.latest': 'Neueste',
    'explore.hot': 'Beliebt',
    'explore.following': 'Folge ich',
    'explore.search_placeholder': 'Beiträge suchen...',
    'explore.no_results': 'Keine Beiträge gefunden',
    'explore.load_more': 'Mehr Laden',
    'explore.trending_tags': 'Trendige Tags',

    // Inspire Page
    'inspire.title': 'Inspiration',
    'inspire.subtitle': 'Lass dich von diesen traditionellen chinesischen Tattoo-Ideen inspirieren',
    'inspire.copy_prompt': 'Idee Kopieren',
    'inspire.copied': 'Kopiert!',

    // Pricing Page
    'pricing.title': 'Mitgliedschaftspläne',
    'pricing.subtitle': 'Wähle den Plan, der am besten zu dir passt',
    'pricing.current_plan': 'Aktueller Plan',
    'pricing.features': 'Funktionen',
    'pricing.unlimited_generations': 'Unbegrenzte Generationen',
    'pricing.priority_support': 'Prioritäts-Support',
    'pricing.exclusive_styles': 'Exklusive Stile',
    'pricing.choose_plan': 'Plan Wählen',

    // Profile Page
    'profile.posts': 'Beiträge',
    'profile.saved': 'Gespeichert',
    'profile.followers': 'Follower',
    'profile.following': 'Folge ich',
    'profile.edit_profile': 'Profil Bearbeiten',
    'profile.follow': 'Folgen',
    'profile.unfollow': 'Entfolgen',
    'profile.no_posts': 'Noch keine Beiträge',

    // Create Page
    'create.title': 'Beitrag Erstellen',
    'create.select_images': 'Bilder Auswählen',
    'create.drag_or_click': 'Bilder hierher ziehen und ablegen oder klicken zum Auswählen',
    'create.post_type': 'Beitragstyp',
    'create.work': 'Tattoo Arbeit',
    'create.idea': 'Idee',
    'create.tattoo_style': 'Tattoo-Stil',
    'create.tags': 'Tags',
    'create.visibility': 'Sichtbarkeit',
    'create.public': 'Öffentlich',
    'create.followers_only': 'Nur Follower',
    'create.private': 'Privat',
    'create.post': 'Veröffentlichen',
    'create.posting': 'Veröffentlichen...',

    // Post Detail
    'post.likes': 'Gefällt mir',
    'post.comments': 'Kommentare',
    'post.share': 'Teilen',
    'post.report': 'Melden',
    'post.write_comment': 'Schreibe einen Kommentar...',
    'post.send': 'Senden',
    'post.delete': 'Löschen',
    'post.edit': 'Bearbeiten',

    // Notifications
    'notifications.title': 'Benachrichtigungen',
    'notifications.mark_all_read': 'Alle als gelesen markieren',
    'notifications.no_notifications': 'Noch keine Benachrichtigungen',
    'notifications.liked': 'hat deinen Beitrag mit \"Gefällt mir\" markiert',
    'notifications.commented': 'hat deinen Beitrag kommentiert',
    'notifications.followed': 'folgt dir jetzt',
    'notifications.save': 'hat deinen Beitrag gespeichert',

    // Artist
    'artist.apply': 'Als Künstler Bewerben',
    'artist.portfolio': 'Portfolio',
    'artist.specialties': 'Spezialgebiete',
    'artist.experience': 'Erfahrung',
    'artist.book_appointment': 'Termin Buchen',
    'artist.view_profile': 'Profil Ansehen',

    // Common Actions
    'action.like': 'Gefällt mir',
    'action.unlike': 'Gefällt mir entfernen',
    'action.save': 'Speichern',
    'action.unsave': 'Entfernen',
    'action.share': 'Teilen',
    'action.report': 'Melden',
    'action.delete': 'Löschen',
    'action.edit': 'Bearbeiten',
    'action.follow': 'Folgen',
    'action.unfollow': 'Entfolgen',

    // Legal
    'legal.terms': 'Nutzungsbedingungen',
    'legal.privacy': 'Datenschutzrichtlinie',
    'legal.disclaimer': 'Haftungsausschluss',
  },
  ko: {
    // Navigation
    'nav.home': '홈',
    'nav.community': '커뮤니티',
    'nav.inspire': '영감',
    'nav.blog': '블로그',
    'nav.artists': '아티스트',
    'nav.upgrade': '업그레이드',
    'nav.apply_artist': '아티스트 신청',
    'nav.sign_in': '로그인',
    'nav.profile': '프로필',
    'nav.notifications': '알림',
    'nav.post': '게시',
    'nav.alerts': '알림',
    'nav.me': '나',
    
    // Home Page - Popular Styles
    'home.popular_styles': '인기 타투 스타일',
    'home.explore_all': '모두 보기',
    'home.trending': '트렌딩',

    // AI Generator
    'ai.title': 'AI 타투 생성기',
    'ai.subtitle': 'AI로 멋진 중국 전통 타투 디자인을 만드세요',
    'ai.style': '스타일',
    'ai.body_part': '신체 부위',
    'ai.prompt_placeholder': '타투 아이디어를 입력하세요...',
    'ai.generate': '타투 생성',
    'ai.generating': '생성 중...',
    'ai.sign_in_to_generate': '로그인하여 생성',
    'ai.preview': '미리보기',
    'ai.download': 'HD 다운로드',
    'ai.share': '공유',
    'ai.your_design': '타투 디자인이 여기에 표시됩니다',
    'ai.upload_image': '참고 이미지 업로드',
    'ai.analyzing': '문화적 의미 분석 중...',

    // Pricing (basic)
    'pricing.free': '무료',
    'pricing.monthly': '월간',
    'pricing.yearly': '연간',
    'pricing.lifetime': '평생',
    'pricing.per_day': '/일',
    'pricing.per_month': '/월',
    'pricing.per_year': '/년',
    'pricing.generations': '생성',
    'pricing.watermark': '워터마크',
    'pricing.no_watermark': '워터마크 없음',
    'pricing.upgrade': '업그레이드',

    // Common
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.success': '성공',
    'common.cancel': '취소',
    'common.confirm': '확인',
    'common.save': '저장',
    'common.delete': '삭제',
    'common.edit': '편집',
    'common.close': '닫기',

    // Body Parts
    'body.arm': '팔',
    'body.back': '등',
    'body.chest': '가슴',
    'body.wrist': '손목',
    'body.collarbone': '쇄골',
    'body.thigh': '허벅지',
    'body.calf': '종아리',

    // Auth - Login
    'auth.welcome_back': '돌아오신 것을 환영합니다',
    'auth.sign_in_to_continue': '계속하려면 로그인하세요',
    'auth.sign_in': '로그인',
    'auth.signing_in': '로그인 중...',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'auth.enter_email': '이메일을 입력하세요',
    'auth.enter_password': '비밀번호를 입력하세요',
    'auth.no_account': '계정이 없으신가요?',
    'auth.sign_up_link': '가입하기',
    'auth.forgot_password': '비밀번호를 잊으셨나요?',

    // Auth - Register
    'auth.create_account': '계정 만들기',
    'auth.join_community': 'InkAI.life 커뮤니티에 가입하세요',
    'auth.username': '사용자 이름',
    'auth.choose_username': '사용자 이름을 선택하세요',
    'auth.create_password': '비밀번호 만들기',
    'auth.creating': '생성 중...',
    'auth.has_account': '이미 계정이 있으신가요?',
    'auth.sign_in_link': '로그인',
    'auth.agree_terms': '동의합니다',
    'auth.terms_of_service': '이용약관',
    'auth.sign_up': '가입하기',
    'auth.sign_in_required': '로그인이 필요합니다',
    'auth.sign_in_desc': '계속하려면 로그인하세요',
    'auth.login_to_post': '작업을 공유하려면 로그인',
    'auth.login_to_post_desc': '타투 애호가 커뮤니티에 가입하세요',
    'auth.login_to_like': '좋아요를 누르려면 로그인',
    'auth.login_to_like_desc': '멋진 작품에 대한 감사를 표현하세요',
    'auth.login_to_comment': '댓글을 달려면 로그인',
    'auth.login_to_comment_desc': '커뮤니티와 생각을 공유하세요',
    'auth.login_to_generate': '만들려면 로그인',
    'auth.login_to_generate_desc': 'AI 타투 디자인 도구에 액세스',
    'auth.login_to_save': '저장하려면 로그인',
    'auth.login_to_save_desc': '좋아하는 디자인을 북마크하세요',
    'auth.login_to_follow': '팔로우하려면 로그인',
    'auth.login_to_follow_desc': '좋아하는 아티스트와 연결하세요',
    'auth.confirm_email': '이메일을 확인하세요',
    'auth.go_to_signin': '로그인으로 이동',

    // Styles
    'style.oriental': '동양풍',
    'style.japanese': '일본풍',
    'style.american_traditional': '미국 전통',
    'style.neo_traditional': '네오 트래디셔널',
    'style.blackwork': '다크 & 블랙워크',
    'style.watercolor': '수채화',
    'style.minimalist': '미니멀리스트',
    'style.realism': '사실주의',

    // Home Page
    'home.hero_title': 'AI로 멋진 중국 전통 타투를 만드세요',
    'home.hero_subtitle': 'AI 기반 타투 디자인 플랫폼',
    'home.hero_description': '아이디어를 몇 초 만에 독특한 타투 아트로 변환하세요. 첨단 AI 기술로 구동됩니다.',
    'home.get_started': '시작하기',
    'home.view_examples': '예시 보기',
    'home.features_title': '핵심 기능',
    'home.featured_works': '추천 작품',
    'home.view_all': '모두 보기',
    'home.cta_title': '시작할 준비가 되셨나요?',
    'home.cta_description': '수천 명의 크리에이터와 함께 다음 타투 영감을 발견하세요.',
    'home.free_signup': '무료 가입',
    'home.feature_ai_title': 'AI 생성',
    'home.feature_ai_desc': '첨단 AI로 독특한 타투 디자인 생성',
    'home.feature_styles_title': '다양한 스타일',
    'home.feature_styles_desc': '중국, 일본, 미국 등 다양한 스타일',
    'home.feature_style_title': '전통적인 스타일',
    'home.feature_style_desc': '진정한 중국 전통 타투 스타일과 문화적 요소를 탐색',
    'home.feature_community_title': '커뮤니티',
    'home.feature_community_desc': '공유하고 다른 사람에게서 영감을 얻으세요',
    'home.feature_artist_title': '전문 아티스트',
    'home.feature_artist_desc': '다음 타투를 위해 인증된 타투 아티스트와 연결',
    'home.how_it_works': '작동 방식',
    'home.step1_title': '비전을 설명하세요',
    'home.step1_desc': '원하는 타투 스타일과 디자인을 알려주세요',
    'home.step2_title': 'AI가 생성합니다',
    'home.step2_desc': 'AI가 설명을 바탕으로 독특한 디자인을 생성',
    'home.step3_title': '다운로드 & 공유',
    'home.step3_desc': '타투 아티스트를 위한 고품질 디자인을 받으세요',

    // Explore Page
    'explore.title': '커뮤니티',
    'explore.recommend': '추천',
    'explore.latest': '최신',
    'explore.hot': '인기',
    'explore.following': '팔로잉',
    'explore.search_placeholder': '게시물 검색...',
    'explore.no_results': '게시물을 찾을 수 없습니다',
    'explore.load_more': '더 보기',
    'explore.trending_tags': '트렌딩 태그',

    // Inspire Page
    'inspire.title': '영감',
    'inspire.subtitle': '전통적인 중국 타투 프롬프트에서 영감을 얻으세요',
    'inspire.copy_prompt': '프롬프트 복사',
    'inspire.copied': '복사됨!',

    // Pricing Page
    'pricing.title': '멤버십 플랜',
    'pricing.subtitle': '가장 적합한 플랜을 선택하세요',
    'pricing.current_plan': '현재 플랜',
    'pricing.features': '기능',
    'pricing.unlimited_generations': '무제한 생성',
    'pricing.priority_support': '우선 지원',
    'pricing.exclusive_styles': '독점 스타일',
    'pricing.choose_plan': '플랜 선택',

    // Profile Page
    'profile.posts': '게시물',
    'profile.saved': '저장됨',
    'profile.followers': '팔로워',
    'profile.following': '팔로잉',
    'profile.edit_profile': '프로필 편집',
    'profile.follow': '팔로우',
    'profile.unfollow': '팔로우 취소',
    'profile.no_posts': '아직 게시물이 없습니다',
    'profile.settings': '설정',
    'profile.display_name': '표시 이름',

    // Create Page
    'create.title': '게시물 만들기',
    'create.select_images': '이미지 선택',
    'create.drag_or_click': '이미지를 드래그 앤 드롭하거나 클릭하여 선택',
    'create.post_type': '게시물 유형',
    'create.work': '타투 작업',
    'create.idea': '아이디어',
    'create.tattoo_style': '타투 스타일',
    'create.tags': '태그',
    'create.visibility': '공개 설정',
    'create.public': '공개',
    'create.followers_only': '팔로워만',
    'create.private': '비공개',
    'create.post': '게시',
    'create.posting': '게시 중...',

    // Post Detail
    'post.likes': '좋아요',
    'post.comments': '댓글',
    'post.share': '공유',
    'post.report': '신고',
    'post.write_comment': '댓글을 작성하세요...',
    'post.send': '보내기',
    'post.delete': '삭제',
    'post.edit': '편집',

    // Notifications
    'notifications.title': '알림',
    'notifications.mark_all_read': '모두 읽음으로 표시',
    'notifications.no_notifications': '아직 알림이 없습니다',
    'notifications.liked': '님이 회원님의 게시물을 좋아합니다',
    'notifications.commented': '님이 회원님의 게시물에 댓글을 달았습니다',
    'notifications.followed': '님이 회원님을 팔로우하기 시작했습니다',
    'notifications.save': '님이 회원님의 게시물을 저장했습니다',

    // Artist
    'artist.apply': '아티스트로 신청',
    'artist.portfolio': '포트폴리오',
    'artist.specialties': '전문 분야',
    'artist.experience': '경력',
    'artist.book_appointment': '예약하기',
    'artist.view_profile': '프로필 보기',

    // Common Actions
    'action.like': '좋아요',
    'action.unlike': '좋아요 취소',
    'action.save': '저장',
    'action.unsave': '저장 취소',
    'action.share': '공유',
    'action.report': '신고',
    'action.delete': '삭제',
    'action.edit': '편집',
    'action.follow': '팔로우',
    'action.unfollow': '팔로우 취소',

    // Legal
    'legal.terms': '이용약관',
    'legal.privacy': '개인정보 처리방침',
    'legal.disclaimer': '면책조항',
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.community': 'Communaute',
    'nav.inspire': 'Inspiration',
    'nav.artists': 'Artistes',
    'nav.upgrade': 'Mise a niveau',
    'nav.apply_artist': 'Postuler Artiste',
    'nav.sign_in': 'Connexion',
    'nav.profile': 'Profil',
    'nav.notifications': 'Notifications',
    'nav.post': 'Publier',
    'nav.alerts': 'Alertes',
    'nav.me': 'Moi',
    
    // Home Page - Popular Styles
    'home.popular_styles': 'Styles de Tatouages Populaires',
    'home.explore_all': 'Explorer Tout',
    'home.trending': 'Tendances',

    // AI Generator
    'ai.title': 'Generateur de Tatouage IA',
    'ai.subtitle': 'Creez des designs de tatouages traditionnels chinois impressionnants avec l\'IA',
    'ai.style': 'Style',
    'ai.body_part': 'Partie du Corps',
    'ai.prompt_placeholder': 'Decrivez votre idee de tatouage...',
    'ai.generate': 'Generer Tatouage',
    'ai.generating': 'Generation...',
    'ai.sign_in_to_generate': 'Connectez-vous pour Generer',
    'ai.preview': 'Apercu',
    'ai.download': 'Telecharger HD',
    'ai.share': 'Partager',
    'ai.your_design': 'Votre design de tatouage apparaitra ici',
    'ai.upload_image': 'Telecharger une image de reference',
    'ai.analyzing': 'Analyse de la signification culturelle...',

    // Pricing (basic)
    'pricing.free': 'Gratuit',
    'pricing.monthly': 'Mensuel',
    'pricing.yearly': 'Annuel',
    'pricing.lifetime': 'A vie',
    'pricing.per_day': '/jour',
    'pricing.per_month': '/mois',
    'pricing.per_year': '/an',
    'pricing.generations': 'generations',
    'pricing.watermark': 'Filigrane',
    'pricing.no_watermark': 'Sans Filigrane',
    'pricing.upgrade': 'Mettre a niveau',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succes',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',

    // Body Parts
    'body.arm': 'Bras',
    'body.back': 'Dos',
    'body.chest': 'Poitrine',
    'body.wrist': 'Poignet',
    'body.collarbone': 'Clavicule',
    'body.thigh': 'Cuisse',
    'body.calf': 'Mollet',

    // Auth - Login
    'auth.welcome_back': 'Bienvenue',
    'auth.sign_in_to_continue': 'Connectez-vous pour continuer votre voyage',
    'auth.sign_in': 'Connexion',
    'auth.signing_in': 'Connexion...',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.enter_email': 'Entrez votre email',
    'auth.enter_password': 'Entrez votre mot de passe',
    'auth.no_account': 'Pas de compte?',
    'auth.sign_up_link': 'S\'inscrire',
    'auth.forgot_password': 'Mot de passe oublie?',

    // Auth - Register
    'auth.create_account': 'Creer un Compte',
    'auth.join_community': 'Rejoindre la communaute InkAI.life',
    'auth.username': 'Nom d\'utilisateur',
    'auth.choose_username': 'Choisissez un nom d\'utilisateur',
    'auth.create_password': 'Creer un mot de passe',
    'auth.creating': 'Creation...',
    'auth.has_account': 'Deja un compte?',
    'auth.sign_in_link': 'Se connecter',
    'auth.agree_terms': 'J\'accepte les',
    'auth.terms_of_service': 'Conditions d\'utilisation',
    'auth.sign_up': 'S\'inscrire',
    'auth.sign_in_required': 'Connexion requise',
    'auth.sign_in_desc': 'Veuillez vous connecter pour continuer',
    'auth.login_to_post': 'Connectez-vous pour partager',
    'auth.login_to_post_desc': 'Rejoignez notre communaute de passionnes de tatouage',
    'auth.login_to_like': 'Connectez-vous pour aimer',
    'auth.login_to_like_desc': 'Montrez votre appreciation pour les oeuvres',
    'auth.login_to_comment': 'Connectez-vous pour commenter',
    'auth.login_to_comment_desc': 'Partagez vos pensees avec la communaute',
    'auth.login_to_generate': 'Connectez-vous pour creer',
    'auth.login_to_generate_desc': 'Accedez aux outils de design de tatouage IA',
    'auth.login_to_save': 'Connectez-vous pour sauvegarder',
    'auth.login_to_save_desc': 'Sauvegardez vos designs favoris',
    'auth.login_to_follow': 'Connectez-vous pour suivre',
    'auth.login_to_follow_desc': 'Connectez-vous avec vos artistes favoris',
    'auth.confirm_email': 'Verifiez votre email',
    'auth.go_to_signin': 'Aller a la connexion',

    // Profile
    'profile.settings': 'Parametres',
    'profile.display_name': 'Nom d\'affichage',

    // Styles
    'style.oriental': 'Oriental',
    'style.japanese': 'Japonais',
    'style.american_traditional': 'Americain Traditionnel',
    'style.neo_traditional': 'Neo Traditionnel',
    'style.blackwork': 'Sombre & Blackwork',
    'style.watercolor': 'Aquarelle',
    'style.minimalist': 'Minimaliste',
    'style.realism': 'Realisme',

    // Home Page
    'home.hero_title': 'Creez des Tatouages Traditionnels Chinois Epoustouflants avec l\'IA',
    'home.hero_subtitle': 'Plateforme de Design de Tatouage propulsee par l\'IA',
    'home.hero_description': 'Transformez vos idees en art de tatouage unique en quelques secondes. Propulse par une technologie IA avancee.',
    'home.get_started': 'Commencer',
    'home.view_examples': 'Voir les Exemples',
    'home.features_title': 'Fonctionnalites Principales',
    'home.featured_works': 'Travaux en Vedette',
    'home.view_all': 'Voir Tout',
    'home.cta_title': 'Pret a Commencer?',
    'home.cta_description': 'Rejoignez des milliers de createurs et decouvrez votre prochaine inspiration de tatouage.',
    'home.free_signup': 'Inscription Gratuite',
    'home.feature_ai_title': 'Generation IA',
    'home.feature_ai_desc': 'Generez des designs de tatouage uniques avec l\'IA avancee',
    'home.feature_styles_title': 'Styles Multiples',
    'home.feature_styles_desc': 'Chinois, Japonais, Americain et plus',
    'home.feature_style_title': 'Styles Traditionnels',
    'home.feature_style_desc': 'Explorez les styles de tatouage traditionnels chinois authentiques',
    'home.feature_community_title': 'Communaute',
    'home.feature_community_desc': 'Partagez et decouvrez l\'inspiration des autres',
    'home.feature_artist_title': 'Artistes Professionnels',
    'home.feature_artist_desc': 'Connectez-vous avec des tatoueurs certifies',
    'home.how_it_works': 'Comment ca Marche',
    'home.step1_title': 'Decrivez Votre Vision',
    'home.step1_desc': 'Dites-nous le style et le design de tatouage que vous voulez',
    'home.step2_title': 'L\'IA Genere',
    'home.step2_desc': 'Notre IA cree des designs uniques bases sur votre description',
    'home.step3_title': 'Telecharger & Partager',
    'home.step3_desc': 'Obtenez des designs de haute qualite prets pour votre tatoueur',

    // Explore Page
    'explore.title': 'Communaute',
    'explore.recommend': 'Pour Vous',
    'explore.latest': 'Recents',
    'explore.hot': 'Populaire',
    'explore.following': 'Abonnements',
    'explore.search_placeholder': 'Rechercher des publications...',
    'explore.no_results': 'Aucune publication trouvee',
    'explore.load_more': 'Charger Plus',
    'explore.trending_tags': 'Tags Tendances',

    // Inspire Page
    'inspire.title': 'Inspiration',
    'inspire.subtitle': 'Inspirez-vous de ces prompts de tatouages traditionnels chinois',
    'inspire.copy_prompt': 'Copier le Prompt',
    'inspire.copied': 'Copie!',

    // Pricing Page
    'pricing.title': 'Plans d\'Adhesion',
    'pricing.subtitle': 'Choisissez le plan qui vous convient le mieux',
    'pricing.current_plan': 'Plan Actuel',
    'pricing.features': 'Fonctionnalites',
    'pricing.unlimited_generations': 'Generations Illimitees',
    'pricing.priority_support': 'Support Prioritaire',
    'pricing.exclusive_styles': 'Styles Exclusifs',
    'pricing.choose_plan': 'Choisir le Plan',

    // Profile Page
    'profile.posts': 'Publications',
    'profile.saved': 'Sauvegardes',
    'profile.followers': 'Abonnes',
    'profile.following': 'Abonnements',
    'profile.edit_profile': 'Modifier le Profil',
    'profile.follow': 'Suivre',
    'profile.unfollow': 'Ne plus suivre',
    'profile.no_posts': 'Pas encore de publications',

    // Create Page
    'create.title': 'Creer une Publication',
    'create.select_images': 'Selectionner des Images',
    'create.drag_or_click': 'Glissez-deposez des images ici ou cliquez pour selectionner',
    'create.post_type': 'Type de Publication',
    'create.work': 'Travail de Tatouage',
    'create.idea': 'Idee',
    'create.tattoo_style': 'Style de Tatouage',
    'create.tags': 'Tags',
    'create.visibility': 'Visibilite',
    'create.public': 'Public',
    'create.followers_only': 'Abonnes uniquement',
    'create.private': 'Prive',
    'create.post': 'Publier',
    'create.posting': 'Publication...',

    // Post Detail
    'post.likes': 'J\'aime',
    'post.comments': 'Commentaires',
    'post.share': 'Partager',
    'post.report': 'Signaler',
    'post.write_comment': 'Ecrire un commentaire...',
    'post.send': 'Envoyer',
    'post.delete': 'Supprimer',
    'post.edit': 'Modifier',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.mark_all_read': 'Tout marquer comme lu',
    'notifications.no_notifications': 'Pas encore de notifications',
    'notifications.liked': 'a aime votre publication',
    'notifications.commented': 'a commente votre publication',
    'notifications.followed': 'a commence a vous suivre',
    'notifications.save': 'a sauvegarde votre publication',

    // Artist
    'artist.apply': 'Postuler comme Artiste',
    'artist.portfolio': 'Portfolio',
    'artist.specialties': 'Specialites',
    'artist.experience': 'Experience',
    'artist.book_appointment': 'Prendre Rendez-vous',
    'artist.view_profile': 'Voir le Profil',

    // Common Actions
    'action.like': 'J\'aime',
    'action.unlike': 'Ne plus aimer',
    'action.save': 'Sauvegarder',
    'action.unsave': 'Ne plus sauvegarder',
    'action.share': 'Partager',
    'action.report': 'Signaler',
    'action.delete': 'Supprimer',
    'action.edit': 'Modifier',
    'action.follow': 'Suivre',
    'action.unfollow': 'Ne plus suivre',

    // Legal
    'legal.terms': 'Conditions d\'Utilisation',
    'legal.privacy': 'Politique de Confidentialite',
    'legal.disclaimer': 'Avis Legal',
  },
  },
};

// Context 类型
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLanguage: { id: Language; name: string; nativeName: string; flag: string };
}

// 默认 Context
const LanguageContext = createContext<LanguageContextType>({
  language: 'zh',
  setLanguage: () => {},
  t: (key: string) => key,
  currentLanguage: LANGUAGES[2], // 默认中文
});

// Storage key
const LANGUAGE_STORAGE_KEY = 'inkai-language';

// Provider 组件
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // 从 localStorage 读取
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (saved && LANGUAGES.find(l => l.id === saved)) {
        return saved as Language;
      }
      // 检测浏览器语言
      const browserLang = navigator.language.split('-')[0];
      const matched = LANGUAGES.find(l => l.id === browserLang);
      if (matched) return matched.id;
    }
    return 'zh'; // 默认中文
  });

  // 保存到 localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    // 更新 HTML lang 属性
    document.documentElement.lang = lang;
  };

  // 翻译函数
  const t = (key: string): string => {
    return translations[language][key] || translations['zh'][key] || key;
  };

  const currentLanguage = LANGUAGES.find(l => l.id === language) || LANGUAGES[2];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Hook
export function useLanguage() {
  return useContext(LanguageContext);
}

// 导出语言列表供组件使用
export type { Language };
