-- ============================================
-- 姝ゆ枃浠剁敱浜戞湇鍔¤嚜鍔ㄧ敓鎴愶紝璇峰嬁鎵嬪姩淇敼
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 鍒涘缓鐢ㄦ埛璧勬枡琛?CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  is_artist BOOLEAN DEFAULT FALSE,
  artist_verified BOOLEAN DEFAULT FALSE,
  location TEXT,
  website TEXT,
  followers_count INTEGER DEFAULT 0,
  following_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 鍒涘缓鐢ㄦ埛鍏虫敞鍏崇郴琛?CREATE TABLE IF NOT EXISTS public.follows (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  follower_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  following_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(follower_id, following_id)
);

-- 鍒涘缓绾硅韩浣滃搧琛?CREATE TABLE IF NOT EXISTS public.tattoo_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT NOT NULL,
  thumbnail_url TEXT,
  style TEXT[], -- 椋庢牸鏍囩
  body_part TEXT, -- 韬綋閮ㄤ綅
  is_ai_generated BOOLEAN DEFAULT FALSE,
  ai_prompt TEXT, -- AI鐢熸垚鎻愮ず璇?  likes_count INTEGER DEFAULT 0,
  comments_count INTEGER DEFAULT 0,
  saves_count INTEGER DEFAULT 0,
  views_count INTEGER DEFAULT 0,
  is_public BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 鍒涘缓浣滃搧鐐硅禐琛?CREATE TABLE IF NOT EXISTS public.post_likes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES public.tattoo_posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(post_id, user_id)
);

-- 鍒涘缓浣滃搧鏀惰棌琛?CREATE TABLE IF NOT EXISTS public.post_saves (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES public.tattoo_posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(post_id, user_id)
);

-- 鍒涘缓璇勮琛?CREATE TABLE IF NOT EXISTS public.comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES public.tattoo_posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  parent_id UUID REFERENCES public.comments(id) ON DELETE CASCADE,
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 鍒涘缓AI鐢熸垚鍘嗗彶琛?CREATE TABLE IF NOT EXISTS public.ai_generations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  prompt TEXT NOT NULL,
  style TEXT,
  body_part TEXT,
  image_url TEXT NOT NULL,
  is_public BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 鍒涘缓绾硅韩甯堜綔鍝侀泦琛?CREATE TABLE IF NOT EXISTS public.artist_portfolios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT NOT NULL,
  style TEXT[],
  price_range TEXT,
  availability BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 鍒涘缓棰勭害/鍜ㄨ琛?CREATE TABLE IF NOT EXISTS public.bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  artist_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending', -- pending, confirmed, completed, cancelled
  message TEXT,
  preferred_date DATE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 鍒涘缓閫氱煡琛?CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- like, comment, follow, booking
  actor_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  post_id UUID REFERENCES public.tattoo_posts(id) ON DELETE CASCADE,
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 鍒涘缓瀛樺偍妗?INSERT INTO storage.buckets (id, name, public)
VALUES ('tattoo-images', 'tattoo-images', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('ai-generated', 'ai-generated', true)
ON CONFLICT (id) DO NOTHING;

-- 鍚敤RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tattoo_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_saves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_portfolios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Profiles RLS绛栫暐
CREATE POLICY "鍏紑璧勬枡鍙煡鐪? ON public.profiles
  FOR SELECT TO anon USING (true);
CREATE POLICY "鐢ㄦ埛鍙洿鏂拌嚜宸辫祫鏂? ON public.profiles
  FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Follows RLS绛栫暐
CREATE POLICY "鍏虫敞鍏崇郴鍏紑鍙" ON public.follows
  FOR SELECT TO anon USING (true);
CREATE POLICY "璁よ瘉鐢ㄦ埛鍙叧娉? ON public.follows
  FOR INSERT TO authenticated WITH CHECK (follower_id = auth.uid());
CREATE POLICY "鐢ㄦ埛鍙彇娑堝叧娉? ON public.follows
  FOR DELETE TO authenticated USING (follower_id = auth.uid());

-- Tattoo posts RLS绛栫暐
CREATE POLICY "鍏紑浣滃搧鍙煡鐪? ON public.tattoo_posts
  FOR SELECT TO anon USING (is_public = true);
CREATE POLICY "鐢ㄦ埛鍙垱寤轰綔鍝? ON public.tattoo_posts
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "鐢ㄦ埛鍙洿鏂拌嚜宸变綔鍝? ON public.tattoo_posts
  FOR UPDATE TO authenticated USING (user_id = auth.uid());
CREATE POLICY "鐢ㄦ埛鍙垹闄よ嚜宸变綔鍝? ON public.tattoo_posts
  FOR DELETE TO authenticated USING (user_id = auth.uid());

-- Likes RLS绛栫暐
CREATE POLICY "鐐硅禐鍏紑鍙" ON public.post_likes
  FOR SELECT TO anon USING (true);
CREATE POLICY "璁よ瘉鐢ㄦ埛鍙偣璧? ON public.post_likes
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "鐢ㄦ埛鍙彇娑堢偣璧? ON public.post_likes
  FOR DELETE TO authenticated USING (user_id = auth.uid());

-- Saves RLS绛栫暐
CREATE POLICY "鐢ㄦ埛鍙煡鐪嬭嚜宸辨敹钘? ON public.post_saves
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "璁よ瘉鐢ㄦ埛鍙敹钘? ON public.post_saves
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "鐢ㄦ埛鍙彇娑堟敹钘? ON public.post_saves
  FOR DELETE TO authenticated USING (user_id = auth.uid());

-- Comments RLS绛栫暐
CREATE POLICY "璇勮鍏紑鍙" ON public.comments
  FOR SELECT TO anon USING (true);
CREATE POLICY "璁よ瘉鐢ㄦ埛鍙瘎璁? ON public.comments
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "鐢ㄦ埛鍙垹闄よ嚜宸辫瘎璁? ON public.comments
  FOR DELETE TO authenticated USING (user_id = auth.uid());

-- AI generations RLS绛栫暐
CREATE POLICY "鐢ㄦ埛鍙煡鐪嬭嚜宸辩敓鎴? ON public.ai_generations
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "鍏紑鐢熸垚鍙煡鐪? ON public.ai_generations
  FOR SELECT TO anon USING (is_public = true);
CREATE POLICY "璁よ瘉鐢ㄦ埛鍙垱寤虹敓鎴? ON public.ai_generations
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

-- Artist portfolios RLS绛栫暐
CREATE POLICY "浣滃搧闆嗗叕寮€鍙" ON public.artist_portfolios
  FOR SELECT TO anon USING (true);
CREATE POLICY "绾硅韩甯堝彲绠＄悊鑷繁浣滃搧" ON public.artist_portfolios
  FOR ALL TO authenticated USING (artist_id = auth.uid());

-- Bookings RLS绛栫暐
CREATE POLICY "鐢ㄦ埛鍙煡鐪嬭嚜宸遍绾? ON public.bookings
  FOR SELECT TO authenticated USING (client_id = auth.uid() OR artist_id = auth.uid());
CREATE POLICY "璁よ瘉鐢ㄦ埛鍙垱寤洪绾? ON public.bookings
  FOR INSERT TO authenticated WITH CHECK (client_id = auth.uid());

-- Notifications RLS绛栫暐
CREATE POLICY "鐢ㄦ埛鍙煡鐪嬭嚜宸遍€氱煡" ON public.notifications
  FOR SELECT TO authenticated USING (user_id = auth.uid());

-- Storage RLS绛栫暐
CREATE POLICY "鍏佽鍖垮悕涓婁紶绾硅韩鍥剧墖" ON storage.objects
  FOR INSERT TO anon WITH CHECK (bucket_id = 'tattoo-images');
CREATE POLICY "鍏佽鍖垮悕鏌ョ湅绾硅韩鍥剧墖" ON storage.objects
  FOR SELECT TO anon USING (bucket_id = 'tattoo-images');
CREATE POLICY "鍏佽鍖垮悕涓婁紶澶村儚" ON storage.objects
  FOR INSERT TO anon WITH CHECK (bucket_id = 'avatars');
CREATE POLICY "鍏佽鍖垮悕鏌ョ湅澶村儚" ON storage.objects
  FOR SELECT TO anon USING (bucket_id = 'avatars');
CREATE POLICY "鍏佽鍖垮悕涓婁紶AI鐢熸垚鍥? ON storage.objects
  FOR INSERT TO anon WITH CHECK (bucket_id = 'ai-generated');
CREATE POLICY "鍏佽鍖垮悕鏌ョ湅AI鐢熸垚鍥? ON storage.objects
  FOR SELECT TO anon USING (bucket_id = 'ai-generated');

-- 鍒涘缓鏂扮敤鎴疯Е鍙戝櫒
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, username, display_name, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'username', 'user_' || substr(NEW.id::text, 1, 8)),
    COALESCE(NEW.raw_user_meta_data ->> 'display_name', 'User'),
    NEW.raw_user_meta_data ->> 'avatar_url'
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();