-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建用户资料表
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  is_artist BOOLEAN DEFAULT FALSE,
  artist_verified BOOLEAN DEFAULT FALSE,
  location TEXT,
  website TEXT,
  followers_count INTEGER DEFAULT 0,
  following_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建用户关注关系表
CREATE TABLE IF NOT EXISTS public.follows (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  follower_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  following_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(follower_id, following_id)
);

-- 创建纹身作品表
CREATE TABLE IF NOT EXISTS public.tattoo_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT NOT NULL,
  thumbnail_url TEXT,
  style TEXT[], -- 风格标签
  body_part TEXT, -- 身体部位
  is_ai_generated BOOLEAN DEFAULT FALSE,
  ai_prompt TEXT, -- AI生成提示词
  likes_count INTEGER DEFAULT 0,
  comments_count INTEGER DEFAULT 0,
  saves_count INTEGER DEFAULT 0,
  views_count INTEGER DEFAULT 0,
  is_public BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建作品点赞表
CREATE TABLE IF NOT EXISTS public.post_likes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES public.tattoo_posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(post_id, user_id)
);

-- 创建作品收藏表
CREATE TABLE IF NOT EXISTS public.post_saves (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES public.tattoo_posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(post_id, user_id)
);

-- 创建评论表
CREATE TABLE IF NOT EXISTS public.comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES public.tattoo_posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  parent_id UUID REFERENCES public.comments(id) ON DELETE CASCADE,
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建AI生成历史表
CREATE TABLE IF NOT EXISTS public.ai_generations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  prompt TEXT NOT NULL,
  style TEXT,
  body_part TEXT,
  image_url TEXT NOT NULL,
  is_public BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建纹身师作品集表
CREATE TABLE IF NOT EXISTS public.artist_portfolios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT NOT NULL,
  style TEXT[],
  price_range TEXT,
  availability BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建预约/咨询表
CREATE TABLE IF NOT EXISTS public.bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  artist_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending', -- pending, confirmed, completed, cancelled
  message TEXT,
  preferred_date DATE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建通知表
CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- like, comment, follow, booking
  actor_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  post_id UUID REFERENCES public.tattoo_posts(id) ON DELETE CASCADE,
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建存储桶
INSERT INTO storage.buckets (id, name, public)
VALUES ('tattoo-images', 'tattoo-images', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('ai-generated', 'ai-generated', true)
ON CONFLICT (id) DO NOTHING;

-- 启用RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tattoo_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_saves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_portfolios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Profiles RLS策略
CREATE POLICY "公开资料可查看" ON public.profiles
  FOR SELECT TO anon USING (true);
CREATE POLICY "用户可更新自己资料" ON public.profiles
  FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Follows RLS策略
CREATE POLICY "关注关系公开可见" ON public.follows
  FOR SELECT TO anon USING (true);
CREATE POLICY "认证用户可关注" ON public.follows
  FOR INSERT TO authenticated WITH CHECK (follower_id = auth.uid());
CREATE POLICY "用户可取消关注" ON public.follows
  FOR DELETE TO authenticated USING (follower_id = auth.uid());

-- Tattoo posts RLS策略
CREATE POLICY "公开作品可查看" ON public.tattoo_posts
  FOR SELECT TO anon USING (is_public = true);
CREATE POLICY "用户可创建作品" ON public.tattoo_posts
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "用户可更新自己作品" ON public.tattoo_posts
  FOR UPDATE TO authenticated USING (user_id = auth.uid());
CREATE POLICY "用户可删除自己作品" ON public.tattoo_posts
  FOR DELETE TO authenticated USING (user_id = auth.uid());

-- Likes RLS策略
CREATE POLICY "点赞公开可见" ON public.post_likes
  FOR SELECT TO anon USING (true);
CREATE POLICY "认证用户可点赞" ON public.post_likes
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "用户可取消点赞" ON public.post_likes
  FOR DELETE TO authenticated USING (user_id = auth.uid());

-- Saves RLS策略
CREATE POLICY "用户可查看自己收藏" ON public.post_saves
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "认证用户可收藏" ON public.post_saves
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "用户可取消收藏" ON public.post_saves
  FOR DELETE TO authenticated USING (user_id = auth.uid());

-- Comments RLS策略
CREATE POLICY "评论公开可见" ON public.comments
  FOR SELECT TO anon USING (true);
CREATE POLICY "认证用户可评论" ON public.comments
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "用户可删除自己评论" ON public.comments
  FOR DELETE TO authenticated USING (user_id = auth.uid());

-- AI generations RLS策略
CREATE POLICY "用户可查看自己生成" ON public.ai_generations
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "公开生成可查看" ON public.ai_generations
  FOR SELECT TO anon USING (is_public = true);
CREATE POLICY "认证用户可创建生成" ON public.ai_generations
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

-- Artist portfolios RLS策略
CREATE POLICY "作品集公开可见" ON public.artist_portfolios
  FOR SELECT TO anon USING (true);
CREATE POLICY "纹身师可管理自己作品" ON public.artist_portfolios
  FOR ALL TO authenticated USING (artist_id = auth.uid());

-- Bookings RLS策略
CREATE POLICY "用户可查看自己预约" ON public.bookings
  FOR SELECT TO authenticated USING (client_id = auth.uid() OR artist_id = auth.uid());
CREATE POLICY "认证用户可创建预约" ON public.bookings
  FOR INSERT TO authenticated WITH CHECK (client_id = auth.uid());

-- Notifications RLS策略
CREATE POLICY "用户可查看自己通知" ON public.notifications
  FOR SELECT TO authenticated USING (user_id = auth.uid());

-- Storage RLS策略
CREATE POLICY "允许匿名上传纹身图片" ON storage.objects
  FOR INSERT TO anon WITH CHECK (bucket_id = 'tattoo-images');
CREATE POLICY "允许匿名查看纹身图片" ON storage.objects
  FOR SELECT TO anon USING (bucket_id = 'tattoo-images');
CREATE POLICY "允许匿名上传头像" ON storage.objects
  FOR INSERT TO anon WITH CHECK (bucket_id = 'avatars');
CREATE POLICY "允许匿名查看头像" ON storage.objects
  FOR SELECT TO anon USING (bucket_id = 'avatars');
CREATE POLICY "允许匿名上传AI生成图" ON storage.objects
  FOR INSERT TO anon WITH CHECK (bucket_id = 'ai-generated');
CREATE POLICY "允许匿名查看AI生成图" ON storage.objects
  FOR SELECT TO anon USING (bucket_id = 'ai-generated');

-- 创建新用户触发器
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, username, display_name, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'username', 'user_' || substr(NEW.id::text, 1, 8)),
    COALESCE(NEW.raw_user_meta_data ->> 'display_name', 'User'),
    NEW.raw_user_meta_data ->> 'avatar_url'
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();