import { motion } from 'framer-motion';
import { AlertTriangle, Shield, Copyright, HeartPulse } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';

export default function Disclaimer() {
  const { t } = useLanguage();
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <h1 className="text-3xl font-bold text-amber-400 mb-4">Disclaimer & Terms</h1>
          <p className="text-slate-400">Please read these important notices before using InkAI.life</p>
        </motion.div>

        <div className="space-y-6">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-slate-900/50 border border-amber-500/20 rounded-2xl p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-amber-500/20 flex items-center justify-center">
                <AlertTriangle className="w-5 h-5 text-amber-400" />
              </div>
              <h2 className="text-xl font-bold text-white">AI Generated Content</h2>
            </div>
            <p className="text-slate-300 leading-relaxed">
              All tattoo designs generated by our AI are for reference and inspiration purposes only. 
              AI-generated images may not perfectly represent the final tattoo result. We recommend 
              consulting with a professional tattoo artist before making any decisions.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-slate-900/50 border border-red-500/20 rounded-2xl p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-red-500/20 flex items-center justify-center">
                <HeartPulse className="w-5 h-5 text-red-400" />
              </div>
              <h2 className="text-xl font-bold text-white">Medical Disclaimer</h2>
            </div>
            <p className="text-slate-300 leading-relaxed">
              Getting a tattoo involves skin penetration and carries inherent risks including infection, 
              allergic reactions, and scarring. This platform does not provide medical advice. Please 
              consult a healthcare professional if you have concerns about skin conditions, allergies, 
              or other health issues related to tattooing.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-slate-900/50 border border-blue-500/20 rounded-2xl p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center">
                <Copyright className="w-5 h-5 text-blue-400" />
              </div>
              <h2 className="text-xl font-bold text-white">Copyright & Intellectual Property</h2>
            </div>
            <p className="text-slate-300 leading-relaxed">
              Users retain rights to their original content uploaded to the platform. AI-generated designs 
              are provided under our terms of service. Respect copyright laws when uploading reference images. 
              Traditional Chinese cultural patterns are part of our shared heritage and should be used respectfully.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-slate-900/50 border border-green-500/20 rounded-2xl p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-green-500/20 flex items-center justify-center">
                <Shield className="w-5 h-5 text-green-400" />
              </div>
              <h2 className="text-xl font-bold text-white">Platform Responsibility</h2>
            </div>
            <p className="text-slate-300 leading-relaxed">
              InkAI.life serves as a platform connecting tattoo enthusiasts, artists, and AI technology. 
              We are not responsible for the quality of tattoos, artist-client relationships, or any 
              disputes arising from services booked through our platform. All transactions and agreements 
              are between users and artists directly.
            </p>
          </motion.div>
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-center mt-12 text-slate-500 text-sm"
        >
          <p>Last updated: May 2025</p>
          <p className="mt-2">By using InkAI.life, you agree to these terms and disclaimers.</p>
        </motion.div>
      </div>
    </div>
  );
}
