import { motion } from 'framer-motion';
import { AlertTriangle, Shield, Copyright, HeartPulse } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';

export default function Disclaimer() {
  const { t, language } = useLanguage();
  const isZh = language === 'zh';
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <h1 className="text-3xl font-bold text-amber-400 mb-4">{t('legal.disclaimer')}</h1>
          <p className="text-slate-400">
            {isZh
              ? '使用 InkAI.life 前，请阅读以下重要声明'
              : 'Please read these important notices before using InkAI.life'}
          </p>
        </motion.div>

        <div className="space-y-6">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-slate-900/50 border border-amber-500/20 rounded-2xl p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-amber-500/20 flex items-center justify-center">
                <AlertTriangle className="w-5 h-5 text-amber-400" />
              </div>
              <h2 className="text-xl font-bold text-white">{isZh ? 'AI 生成内容 / AI Generated Content' : 'AI Generated Content'}</h2>
            </div>
            <p className="text-slate-300 leading-relaxed">
              {isZh
                ? '我们 AI 生成的所有纹身设计仅供参考和灵感启发。AI 生成的图像可能无法完美呈现最终的纹身效果。我们建议在做出任何决定之前咨询专业纹身师。'
                : 'All tattoo designs generated by our AI are for reference and inspiration purposes only. AI-generated images may not perfectly represent the final tattoo result. We recommend consulting with a professional tattoo artist before making any decisions.'}
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-slate-900/50 border border-red-500/20 rounded-2xl p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-red-500/20 flex items-center justify-center">
                <HeartPulse className="w-5 h-5 text-red-400" />
              </div>
              <h2 className="text-xl font-bold text-white">{isZh ? '医疗免责声明 / Medical Disclaimer' : 'Medical Disclaimer'}</h2>
            </div>
            <p className="text-slate-300 leading-relaxed">
              {isZh
                ? '纹身涉及皮肤穿刺，存在感染、过敏反应和瘤痕等固有风险。本平台不提供医疗建议。如果您对皮肤状况、过敏或其他与纹身相关的健康问题有疑虑，请咨询医疗专业人士。'
                : 'Getting a tattoo involves skin penetration and carries inherent risks including infection, allergic reactions, and scarring. This platform does not provide medical advice. Please consult a healthcare professional if you have concerns about skin conditions, allergies, or other health issues related to tattooing.'}
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-slate-900/50 border border-blue-500/20 rounded-2xl p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center">
                <Copyright className="w-5 h-5 text-blue-400" />
              </div>
              <h2 className="text-xl font-bold text-white">{isZh ? '版权与知识产权 / Copyright & Intellectual Property' : 'Copyright & Intellectual Property'}</h2>
            </div>
            <p className="text-slate-300 leading-relaxed">
              {isZh
                ? '用户保留其上传到平台的原创内容的权利。AI 生成的设计根据我们的服务条款提供。上传参考图片时请尊重版权法。中国传统纹样是我们共同文化遗产的一部分，应当被尊重使用。'
                : 'Users retain rights to their original content uploaded to the platform. AI-generated designs are provided under our terms of service. Respect copyright laws when uploading reference images. Traditional Chinese cultural patterns are part of our shared heritage and should be used respectfully.'}
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-slate-900/50 border border-green-500/20 rounded-2xl p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-green-500/20 flex items-center justify-center">
                <Shield className="w-5 h-5 text-green-400" />
              </div>
              <h2 className="text-xl font-bold text-white">{isZh ? '平台责任 / Platform Responsibility' : 'Platform Responsibility'}</h2>
            </div>
            <p className="text-slate-300 leading-relaxed">
              {isZh
                ? 'InkAI.life 作为连接纹身爱好者、艺术家和 AI 技术的平台。我们对纹身质量、艺术家与客户之间的关系或通过我们平台预约的服务产生的任何争议不承担责任。所有交易和协议均在用户和艺术家之间直接进行。'
                : 'InkAI.life serves as a platform connecting tattoo enthusiasts, artists, and AI technology. We are not responsible for the quality of tattoos, artist-client relationships, or any disputes arising from services booked through our platform. All transactions and agreements are between users and artists directly.'}
            </p>
          </motion.div>
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-center mt-12 text-slate-500 text-sm"
        >
          <p>Last updated: May 2025</p>
          <p className="mt-2">
            {isZh
              ? '使用 InkAI.life 即表示您同意这些条款和免责声明。'
              : 'By using InkAI.life, you agree to these terms and disclaimers.'}
          </p>
        </motion.div>
      </div>
    </div>
  );
}
